### ISSUE TITLE
Change UUIDs (windows installer?)

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#122]
`accessible/interfaces/msaa/ISimpleDOMDocument.idl`
`accessible/interfaces/msaa/ISimpleDOMNode.idl`
`accessible/interfaces/msaa/ISimpleDOMText.idl`
`accessible/ipc/win/handler/HandlerData.idl` => check from diff https://github.com/ghostery/user-agent-desktop/pull/6/files#diff-0d474b24494021921fffed90235f3bfd
Original commit: https://github.com/cliqz-oss/browser-f/commit/41db3bd08d88bac10321ee42877925f327b3a1de
File: https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/accessible/interfaces/msaa/ISimpleDOMDocument.idl#L61

Seems to be related to Windows installer?

**Comment by sammacbeth** [comment]
see my comment here: https://github.com/ghostery/user-agent-desktop/issues/37#issuecomment-697178964

**Comment by sammacbeth** [comment]
Regarding the content of the mentioned browser-f commit:
 * UUID change - not sure what it fixes, but seems to work with changing, so let's leave it.
 * `module.ver` changes - #247 
 * Rename `FirefoxHTML` to `{Brand}HTML`. I think it's safe to leave this change, the registry entries have an installation ID appended, so it should not conflict with Firefox installs.
 * `version_win.pl` these changes are not needed as the `module.ver` file provides overrides for these values.
