### ISSUE TITLE
Remove Google Safe Browsing

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#123]
`browser/actors/BlockedSiteChild.jsm` (line 87) https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/actors/BlockedSiteChild.jsm#L88

Jira: https://cliqztix.atlassian.net/browse/DB-2442
Jira 2: https://cliqztix.atlassian.net/browse/DB-2510

Original PR: https://github.com/cliqz-oss/browser-f/pull/1515/files (Mozilla => Cliqz?)
PR 2: https://github.com/cliqz-oss/browser-f/pull/1561 (replace Cliqz => Mozilla?)

`modules/libpref/init/all.js`
Check prefs with `browser.safebrowsing` prefix

**Comment by chrmod** [comment]
How about we keep it? Do we have to pay for Google API?

**Comment by remusao** [comment]
Closing for now, will have a follow-up to proxy calls.
