### ISSUE TITLE
Parameterize Firefox hard-coded

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#126]
`browser/app/macbuild/Contents/Info.plist.in` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/macbuild/Contents/Info.plist.in#L166
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/macbuild/Contents/Info.plist.in#L168
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/macbuild/Contents/Info.plist.in#L180
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/macbuild/Contents/Info.plist.in#L182

This replaces some usage of hard-coded firefox string with `%MOZ_APP_NAME%`

`browser/app/module.ver` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/module.ver#L1
`browser/app/nsBrowserApp.cpp` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/nsBrowserApp.cpp#L121

**Comment by chrmod** [comment]
At first we should look on those hardcoded string and replace them with our own. The next should be to parameterise them and ship patches to upstream.

**Comment by sammacbeth** [comment]
* Mac Info.plist changes we already patched, and this was also fixed upstream.
 * `module.ver` changes are in #247 
 * `nsBrowserApp.app` - I'm not sure what this is for. I suggest to leave it for the time being.

**Comment by chrmod** [comment]
Can this be covered by https://github.com/ghostery/user-agent-desktop/issues/176 ?

**Comment by sammacbeth** [comment]
These changes have all already been covered, so it's safe to close.
