### ISSUE TITLE
Force more frequent updates on beta channel

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#128]
`browser/app/profile/firefox.js` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L181

PR: https://github.com/cliqz-oss/browser-f/commit/6d5669bdc47e02aba2ed43612f2b4515da0c4f92

**Comment by chrmod** [comment]
Does not apply to UA project as we won't ship system addon updates
