### ISSUE TITLE
Disable Firefox UI Tour

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#130]
`browser/app/profile/firefox.js` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L202

**Comment by chrmod** [comment]
Let's take a look on https://github.com/ghostery/user-agent-desktop/issues/148 to check if pref is sufficient

**Comment by sammacbeth** [comment]
Testing locally, disabling this pref does not remove the 'Ghostery Tour' option in the help menu. This option is now more forcibly removed in #240 but comment out the relevant markpu. Is there another entrypoint to this feature that would require us to also disable this via pref?

**Comment by chrmod** [comment]
I cannot find any other entry point. Closing for now.
