### ISSUE TITLE
Custom prefs in firefox.js

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#131]
`browser/app/profile/firefox.js`

* `pref("browser.startup.restoreTabs", false);` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L260
* `pref("browser.startup.addFreshTab", true);` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L264
* `pref("browser.slowStartup.notificationDisabled", true);` (default: false) https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L285
* `pref("browser.urlbar.suggest.searches", false);` (default: true) https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L323
* `pref("browser.urlbar.userMadeSearchSuggestionsChoice", true);` + `pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L336
* `pref("browser.search.geoSpecificDefaults", false);` (default: true) https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L419
* `pref("browser.tabs.tabClipWidth", 1);` (default: 140) https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L510 `// CLIQZ DB-1418: Allow more tabs' close button to be visible`
* `pref("browser.newtab.preload", false);` (default: true) https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1306
* `pref("browser.library.activity-stream.enabled", false);` (default: true) https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1313
* `pref("browser.aboutwelcome.enabled", false);` (default: true) https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1373
* `pref("toolkit.startup.max_resumed_crashes", -1);` (default: 3) https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1395 `number of startup crashes that can occur before starting into safe mode automatically`
* `pref("blockautoplay.whitelist.add", "https://www.youtube.com/");` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1545 (Make sure autoplay blocking is disabled for YouTube)

**Comment by sammacbeth** [comment]
* `browser.startup.restoreTabs` - This pref is no longer used in firefox source
 * `browser.startup.addFreshTab` - ditto
 * `browser.slowStartup.notificationDisabled` - Telemetry is disabled so this won't send, but we might as well avoid entering that code block.
 * `browser.urlbar.suggest.searches` - Refers to the "Show search suggestions in address bar results" setting in search preferences. Probably should stay on.
 * `browser.urlbar.userMadeSearchSuggestionsChoice` + `browser.urlbar.timesBeforeHidingSuggestionsHint` - No longer exist
 * `browser.search.geoSpecificDefaults` - I only find use of this in tests...
 * `browser.tabs.tabClipWidth` - Not sure what this does...
 * `browser.newtab.preload` - We should probably keep this on to have snappy new-tab behaviour. Maybe @chrmod knows what it was disabled?
 * `browser.library.activity-stream.enabled` - yes let's disable this
 * `browser.aboutwelcome.enabled` - this one too
 * `toolkit.startup.max_resumed_crashes` - @chrmod do you know why we changed this one?
 * `blockautoplay.whitelist.add` - Not sure this is needed.

**Comment by chrmod** [comment]
>     * `browser.newtab.preload` - We should probably keep this on to have snappy new-tab behaviour. Maybe @chrmod knows what it was disabled?

If possible I would like to keep it.

>     * `toolkit.startup.max_resumed_crashes` - @chrmod do you know why we changed this one?

Nope

**Comment by sammacbeth** [comment]
Update on `browser.library.activity-stream.enabled` - disabling this removes the 'Recent Highlights' section of the Library.
<img width="292" alt="Screenshot 2020-09-24 at 14 09 14" src="https://user-images.githubusercontent.com/248111/94143094-a0c03f00-fe6f-11ea-9635-f4d29eb98a89.png">
