### ISSUE TITLE
Lock Extension icon in toolbar

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#134]
`mozilla-release/browser/base/content/browser-pageActions.js` => https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser-pageActions.js#L926
`mozilla-release/browser/base/content/browser.js` https://github.com/cliqz-oss/browser-f/commit/5f765d66c65af066662c749c5d1c3226bc269fb1#diff-0e645ddb33aacd21d10cbf358fe45140
`mozilla-release/browser/base/content/browser.xul` https://github.com/cliqz-oss/browser-f/commit/5f765d66c65af066662c749c5d1c3226bc269fb1#diff-0a456036a5b2ad512ea9657e18f5fe2f
`mozilla-release/browser/components/customizableui/content/panelUI.inc.xul` https://github.com/cliqz-oss/browser-f/commit/5f765d66c65af066662c749c5d1c3226bc269fb1#diff-c72ea6f6a4de663b6830595e8aeb039d

https://github.com/cliqz-oss/browser-f/commit/5f765d66c65af066662c749c5d1c3226bc269fb1

Here we can customize the layout of user interface with a pref: `browser/app/profile/firefox.js`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1456

`browser/components/customizableui/CustomizableUI.jsm` (customize navbar placement)
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/customizableui/CustomizableUI.jsm#L230

In general the UI can be customize from this file https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/customizableui/CustomizableUI.jsm
Check this file `browser/components/customizableui/CustomizableUI.jsm` in Firefox/Cliqz Diff for more details.

`browser/components/customizableui/moz.build` (seems required to allow preprocessing UI jsm files)
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/customizableui/moz.build#L24

**Comment by chrmod** [comment]
Natural move would be to put Ghostery icon in place where tracking protection icon used to be (left side of urlbar).
