### ISSUE TITLE
Disable Protections reports

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#136]
Lockwise, password manager (maybe related to warning if passwords have been leaked?)
`pref("browser.contentblocking.report.monitor.enabled", false);` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1680
`pref("browser.contentblocking.report.lockwise.enabled", false);` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1683

There are other prefs which were not touched but maybe we want to customize them as well.

**Comment by sammacbeth** [comment]
These refer to two sections of the `about:protections`, for data breach report and password manager respectively. #125 Removes links to this page so I don't think we need to touch these prefs.
