### ISSUE TITLE
Disable Screenshots?

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#138]
`browser/app/profile/firefox.js`
`pref("extensions.screenshots.disabled", true);` => https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1928
`pref("extensions.screenshots.upload-disabled", true);` => https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1931

**Comment by chrmod** [comment]
I suppose this disabled screenshots the hard way https://github.com/ghostery/user-agent-desktop/pull/112
