### ISSUE TITLE
Disable Normandy

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#139]
`browser/app/profile/firefox.js`
`pref("app.normandy.enabled", false);` => https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1957

**Comment by sammacbeth** [comment]
Disabled via this patch:
https://github.com/ghostery/user-agent-desktop/blob/9ceebd0d47219dae073e4db10169aee349dc7bd1/patches/0011-Force-healthreport-and-normandy-off-at-configure-tim.patch#L22-L23

This is stronger than the pref, as normandy is excluded at compile time.

**Comment by chrmod** [comment]
Woudn't setting the `MOZ_NORMANY` flag in the branding folder work as well and not require a patch?

**Comment by sammacbeth** [comment]
> Woudn't setting the `MOZ_NORMANY` flag in the branding folder work as well and not require a patch?

This didn't work for me. `imply_option` seems to act as a default value, but I'm not sure how to set it to false explicitly.
