### ISSUE TITLE
Disable Data Reporting

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#140]
`MOZ_DATA_REPORTING` is a constant which can be used to disable different services:
* Normandy https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L1964

**Comment by sammacbeth** [comment]
Disabled via mozconfig: https://github.com/ghostery/user-agent-desktop/blob/9ceebd0d47219dae073e4db10169aee349dc7bd1/brands/ghostery/mozconfig#L8
