### ISSUE TITLE
Disable Corroborator

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#141]
Comment says `Check bundled omni JARs for corruption.`
It was disabled in Cliqz. https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/profile/firefox.js#L2022

**Comment by chrmod** [comment]
Corraborator depends on Mozilla telemetry so there is no value in it without having one.

**Comment by chrmod** [comment]
Corroborator depends on Mozilla telemetry so there is no value in it without having one.

**Comment by sammacbeth** [comment]
Also it only checks against Mozilla certs, so let's disable. https://searchfox.org/mozilla-central/source/toolkit/components/corroborator/Corroborate.jsm#66
