### ISSUE TITLE
Disable Telemetry

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#142]
Grep for `incoming.telemetry.mozilla.org` => replaced with `reports.cliqz.com`.

Relevant Pull Request: https://github.com/cliqz-oss/browser-f/pull/1546
Relevant Jira: https://cliqztix.atlassian.net/browse/DB-2499

`browser/app/winlauncher/ErrorHandler.cpp`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/winlauncher/ErrorHandler.cpp#L52
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/winlauncher/ErrorHandler.cpp#L53
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/app/winlauncher/ErrorHandler.cpp#L85

`browser/installer/windows/nsis/defines.nsi.in`
https://github.com/cliqz-oss/browser-f/commit/e2d4676fb3832c2df72edd5aece0b953ae8c957c#diff-be9de7018890a8accff8e031ebccf289

`build/submit_telemetry_data.py`
https://github.com/cliqz-oss/browser-f/commit/e2d4676fb3832c2df72edd5aece0b953ae8c957c#diff-2cbb87f1b430cab20849b1226a5cc055

This also handles *SSL error reports* (are those disabled)?
https://github.com/cliqz-oss/browser-f/commit/e2d4676fb3832c2df72edd5aece0b953ae8c957c#diff-35d36492a522c301915e005175aaf814
`modules/libpref/init/all.js` https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/modules/libpref/init/all.js#L158

`build/submit_telemetry_data.py`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/build/submit_telemetry_data.py#L22

`modules/libpref/init/all.js`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/modules/libpref/init/all.js#L811
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/modules/libpref/init/all.js#L813

**Comment by chrmod** [comment]
My hope is that setting the pref that disable telemetry will be enough https://github.com/ghostery/user-agent-desktop/blob/eed722d68ea673192ea8053e345da961a7eb14f5/branding/ghostery/pref/firefox-branding.js#L61 

In case we find during https://github.com/ghostery/user-agent-desktop/issues/198 that there are still calls being make to telemetry system we should revisit this issue.
