### ISSUE TITLE
Disable Health Report

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#143]
Look for `MOZ_SERVICES_HEALTHREPORT` (Can we disable that somewhere?)

`modules/libpref/init/all.js`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/modules/libpref/init/all.js#L4725

**Comment by sammacbeth** [comment]
This is now disabled here: https://github.com/ghostery/user-agent-desktop/blob/e5cea690c4fac6023dbb74fd15f4d6d84d62d404/patches/0011-Force-healthreport-and-normandy-off-at-configure-tim.patch#L17-L18
