### ISSUE TITLE
Customize About Dialog

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#144]
`browser/base/content/aboutDialog.css`
Disable background `about-wordmark.svg` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/aboutDialog.css#L16
https://github.com/cliqz-oss/browser-f/pull/580 (Might not be relevant anymore)

Changes in the following files as well:
`browser/base/content/aboutDialog.xhtml`
`browser/locales/en-US/browser/aboutDialog.ftl`
`browser/base/content/aboutDialog.xul`
`browser/base/content/aboutDialog.js`
This seems to be related to changing the versioning scheme so maybe not relevant anymore?
Commit: https://github.com/cliqz-oss/browser-f/commit/1e71057f9bd22d8a1551b0f01deaee37e7bf57f3
Jira: https://cliqztix.atlassian.net/browse/DB-1148

Maybe we don't need all of that anymore? @chrmod

Some localized files
`browser/locales/en-US/browser/aboutDialog.ftl`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/browser/aboutDialog.ftl

**Comment by chrmod** [comment]
@sammacbeth isn't it covered by https://github.com/ghostery/user-agent-desktop/pull/116 ? if so, please close this one
