### ISSUE TITLE
Disable Pocket

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#147]
Seems pretty complicated to remove Pocket. Maybe there is an easier way?

`browser/base/content/browser-context.inc` (remove from menu)
PR: https://github.com/cliqz-oss/browser-f/pull/1218
Jira: https://cliqztix.atlassian.net/browse/DB-2091

`browser/base/content/browser.xhtml`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser.xhtml#L555
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser.xhtml#L1097

`browser/components/BrowserGlue.jsm`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/BrowserGlue.jsm#L825
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/BrowserGlue.jsm#L1430

`browser/components/customizableui/content/panelUI.inc.xhtml`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/customizableui/content/panelUI.inc.xhtml#L808

`browser/components/moz.build`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/moz.build#L47

`browser/components/newtab/lib/TopStoriesFeed.jsm`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/newtab/lib/TopStoriesFeed.jsm#L37
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/newtab/lib/TopStoriesFeed.jsm#L167
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/newtab/lib/TopStoriesFeed.jsm#L174

`toolkit/modules/NewTabUtils.jsm`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/modules/NewTabUtils.jsm#L49
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/modules/NewTabUtils.jsm#L1065
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/modules/NewTabUtils.jsm#L1557
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/modules/NewTabUtils.jsm#L1576
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/modules/NewTabUtils.jsm#L1644

**Comment by chrmod** [comment]
I've hoped this would be enough https://github.com/ghostery/user-agent-desktop/blob/d9c4315a2261ba58d13ae010a5e5890e9b0fcbc2/branding/ghostery/pref/firefox-branding.js#L100 - have to check if it holds

**Comment by chrmod** [comment]
Closing for now as flipping the pref seems to do the job.
