### ISSUE TITLE
Custom about pages

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#150]
When we added custom `about:cliqz`

`browser/base/content/browser-siteIdentity.js`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser-siteIdentity.js#L60
```js
/**
 * RegExp used to decide if an about url should be shown as being part of
 * the browser UI.
 */
```

**Comment by chrmod** [comment]
Good to know. @sammacbeth please take a look. Nothing to action for now
