### ISSUE TITLE
Shield for Tracking Protection

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#151]
`browser/base/content/browser-siteIdentity.js`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser-siteIdentity.js#L904

`browser/base/content/browser.js` (look for `gProtectionsHandler`)
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser.js#L182
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser.js#L2098
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser.js#L2615
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser.js#L5291

Relevant commit: https://github.com/cliqz-oss/browser-f/commit/b9564e9aa9ae48d309ba455a805255fb76d329f2

**Comment by chrmod** [comment]
@sammacbeth is this covered by #125? if so, please close this one
