### ISSUE TITLE
Custom browser theme

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#154]
Maybe useful for custom Ghostery theming?
`browser/base/content/browser.js` => https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser.js#L638
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser.js#L1882

`browser/base/content/browser.xhtml`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser.xhtml#L32
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/content/browser.xhtml#L65

`browser/components/customizableui/CustomizeMode.jsm` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/customizableui/CustomizeMode.jsm
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/customizableui/CustomizeMode.jsm#L15
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/customizableui/CustomizeMode.jsm#L167
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/customizableui/CustomizeMode.jsm#L200
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/customizableui/CustomizeMode.jsm#L1784

`browser/components/customizableui/content/customizeMode.inc.xhtml`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/customizableui/content/customizeMode.inc.xhtml#L35

`browser/locales/en-US/browser/customizeMode.ftl`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/browser/customizeMode.ftl

**Comment by chrmod** [comment]
There are few way we can implement custom theme so those notes should help to make a decission.

**Comment by chrmod** [comment]
Related or duplicated https://github.com/ghostery/user-agent-desktop/issues/25

**Comment by chrmod** [comment]
```
These files are relevant:

- [ ] `browser/components/customizableui/CustomizableUI.jsm` --- https://github.com/human-web/user-agent-desktop/pull/6/files#diff-ddc2ca7bc8d3d98442f59dfcf1dc786e
- [ ] `browser/components/customizableui/CustomizeMode.jsm` --- https://github.com/human-web/user-agent-desktop/pull/6/files#diff-c38ff6b75a6a6bbe56dd6c5b58dae84d
- [ ] `browser/components/customizableui/content/customizeMode.inc.xhtml` --- https://github.com/human-web/user-agent-desktop/pull/6/files#diff-8cd6a01342ebe83c8ecb331f91114ad2R35
- [ ] `browser/components/customizableui/content/panelUI.inc.xhtml` --- https://github.com/human-web/user-agent-desktop/pull/6/files#diff-ad6640a26ab448decc59c78c926db5f3
- [ ] https://github.com/human-web/user-agent-desktop/pull/6/files#diff-6b973edde56b845f639ad5316d3f14a3R24-R27
```
Closing https://github.com/ghostery/user-agent-desktop/issues/25 as a duplicate

**Comment by chrmod** [comment]
Looks like we wont need that level of customization
