### ISSUE TITLE
Customized Files to be bundled

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#157]
`browser/base/jar.mn` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/base/jar.mn

Might be useful to:
* Apply preprocessor to files (if we rely on commenting out parts with `#if 0`, etc.)
* Add new files

**Comment by chrmod** [comment]
Good to remember but is not very actionable. 
@sammacbeth please take a look
