### ISSUE TITLE
Custom Branding

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#158]
`browser/branding/branding-common.mozbuild` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/branding/branding-common.mozbuild
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/branding/branding-common.mozbuild#L20
Customize `cliqz.VisualElementsManifest.xml`

**Comment by chrmod** [comment]
fixed by https://github.com/ghostery/user-agent-desktop/issues/167 and others
