### ISSUE TITLE
Disable New Install Onboarding

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#159]
`browser/components/BrowserContentHandler.jsm` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/BrowserContentHandler.jsm

https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/BrowserContentHandler.jsm#L45

This file is also relevant if we want to show a what's new page on update.
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/BrowserContentHandler.jsm#L131

`browser/components/about/components.conf`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/about/components.conf#L24

**Comment by sammacbeth** [comment]
I believe we can push new tabs on update with balrog. We should test this.

I'm not sure about the other changes here. There is currently no onboarding triggered (except from Ghostery extension).

**Comment by chrmod** [comment]
As tested, the new install onboarding does not fire on new profiles at the moment. For the updates we can try to use balrog. Anyways, nothing to do for now. Closing for now.
