### ISSUE TITLE
Disable Discovery

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#162]
`browser/components/BrowserGlue.jsm`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/BrowserGlue.jsm#L793
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/BrowserGlue.jsm#L2435

**Comment by sammacbeth** [comment]
We can disable this feature via pref, rather than with a code change: https://searchfox.org/mozilla-central/source/browser/modules/Discovery.jsm#24

**Comment by sammacbeth** [comment]
...and it looks like we have already set that pref: https://github.com/ghostery/user-agent-desktop/blob/204e9a987886c4d41ed34acc68f6d608ff2e5b48/brands/ghostery/branding/pref/firefox-branding.js#L103
