### ISSUE TITLE
Customise Lockwise and Logins?

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#166]
Should we?
Related: `about:logins`
Or maybe branding is enough here?

`browser/components/about/components.conf` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/about/components.conf

Seems like Cliqz forced the use of legacy password manager instead of Lockwise.

**Comment by sammacbeth** [comment]
I would personally go for rebranding. There is a small amount of copy to update, some links to remove:
 * Three dot menu on `about:logins` - remove lockwise links and update/remove help link.
<img width="254" alt="Screenshot 2020-09-14 at 17 27 58" src="https://user-images.githubusercontent.com/248111/93105694-abc8e180-f6af-11ea-89e0-cc4da27a1949.png">
 * Logins and Passwords on `about:preferences` - remove breach alert setting
<img width="654" alt="Screenshot 2020-09-14 at 17 29 12" src="https://user-images.githubusercontent.com/248111/93105884-dfa40700-f6af-11ea-972e-0c784d1aa5c8.png">
 * `about:logins` - update onboarding copy
<img width="395" alt="Screenshot 2020-09-14 at 17 30 03" src="https://user-images.githubusercontent.com/248111/93105966-f9454e80-f6af-11ea-8b68-15d19c502b2a.png">

**Comment by chrmod** [comment]
IMAO, a password manager solve this problem very well and as we don't have a plan to provide Sync service right now I would rather remove this feature from the browser completely.

**Comment by remusao** [comment]
> IMAO, a password manager solve this problem very well and as we don't have a plan to provide Sync service right now I would rather remove this feature from the browser completely.

Lockwise *is* a password manager and I could see how it's useful to users not having a separate password manager (which I would expect to be most users).

**Comment by sammacbeth** [comment]
> IMAO, a password manager solve this problem very well and as we don't have a plan to provide Sync service right now I would rather remove this feature from the browser completely.

Note, from what I can tell the latest Cliqz version also does not disable `about:logins`.

**Comment by chrmod** [comment]
Alright, lets keep logins and passwords, but remove all Mozilla/Lockwise/Sync references.
