### ISSUE TITLE
Allow Migrating from Firefox to Ghostery

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#167]
`browser/components/migration/FirefoxProfileMigrator.jsm` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/FirefoxProfileMigrator.jsm
I think there is another issue open for this already.

`browser/components/migration/MigrationUtils.jsm` (allow Cliqz to import from Firefox at any point of time, not only on install)
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/MigrationUtils.jsm#L458

`browser/components/migration/components.conf`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/components.conf#L35

`browser/components/migration/content/migration.js` (check this file from diff)
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/content/migration.js

`browser/components/migration/content/migration.xhtml`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/content/migration.xhtml

`browser/components/migration/moz.build`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/moz.build

`browser/components/migration/nsIBrowserProfileMigrator.idl`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/nsIBrowserProfileMigrator.idl

`browser/locales/en-US/chrome/browser/migration/migration.properties` (settings?)
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/chrome/browser/migration/migration.properties

**Comment by chrmod** [comment]
When we should tackle it? Open Beta or First release?

**Comment by chrmod** [comment]
Browser-f diffs https://github.com/cliqz-oss/browser-f/commit/5800867b175168e39129176c2663cc839d72da44
