### ISSUE TITLE
Make sure all about pages are customized

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#168]
Let's check `about:about` to make sure we customize (e.g. `about:welcome` in `browser/components/migration/content/aboutWelcomeBack.xhtml` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/content/aboutWelcomeBack.xhtml)

`browser/locales/en-US/browser/aboutSessionRestore.ftl`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/browser/aboutSessionRestore.ftl

**Comment by chrmod** [comment]
Covered by other issues already
