### ISSUE TITLE
Customize Private Browsing Page (Forget Mode)

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#169]
`browser/components/privatebrowsing/jar.mn`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/privatebrowsing/jar.mn#L6

`browser/locales/en-US/browser/aboutPrivateBrowsing.ftl`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/browser/aboutPrivateBrowsing.ftl

`browser/locales/en-US/browser/appMenuNotifications.ftl`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/browser/appMenuNotifications.ftl

`browser/locales/en-US/browser/browser.ftl`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/browser/browser.ftl

`browser/locales/en-US/browser/browserContext.ftl`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/browser/browserContext.ftl

`browser/locales/en-US/browser/menubar.ftl`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/browser/menubar.ftl

`browser/locales/en-US/browser/newtab/newtab.ftl`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/browser/newtab/newtab.ftl

`browser/locales/en-US/chrome/browser/browser.dtd`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/chrome/browser/browser.dtd

`browser/locales/en-US/chrome/browser/browser.properties`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/chrome/browser/browser.properties

`browser/locales/en-US/chrome/browser/customizableui/customizableWidgets.properties`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/chrome/browser/customizableui/customizableWidgets.properties

`browser/locales/en-US/chrome/browser/places/places.dtd`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/chrome/browser/places/places.dtd

`browser/locales/en-US/chrome/browser/tabbrowser.properties`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/chrome/browser/tabbrowser.properties

`browser/locales/en-US/chrome/browser/taskbar.properties`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/chrome/browser/taskbar.properties

`toolkit/locales/en-US/chrome/mozapps/downloads/downloads.properties`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/locales/en-US/chrome/mozapps/downloads/downloads.properties

`toolkit/locales/en-US/chrome/mozapps/handling/handling.properties`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/locales/en-US/chrome/mozapps/handling/handling.properties

**Comment by chrmod** [comment]
`Ghost Mode` is a signature feature of Ghostery Mobile browsers. I would say this is a great branding option and we should include it in Open Beta.

**Comment by sammacbeth** [comment]
For the new private tab page we can custom alot with branding. See CSS [here](https://searchfox.org/mozilla-central/source/browser/themes/shared/privatebrowsing)
