### ISSUE TITLE
Customize App Name

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#172]
Do we need this?
`browser/confvars.sh`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/confvars.sh#L6

**Comment by chrmod** [comment]
nope, it is already covered by https://github.com/ghostery/user-agent-desktop/blob/5e6af595cf95d5f118f74fe0abf81bd495587c9e/branding/ghostery/configure.sh#L6
