### ISSUE TITLE
Customize Installer (Mini installer?)

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#173]
Is this relevant for all platforms or just Windows?

`browser/installer/package-manifest.in`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/installer/package-manifest.in#L132
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/installer/package-manifest.in#L152 (Package adult domains)
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/installer/package-manifest.in#L496 (Extra distribution files?)

`browser/installer/windows/Makefile.in` (extra branding files for Windows installer)
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/installer/windows/Makefile.in#L41

`browser/installer/windows/app.tag`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/installer/windows/app.tag#L2

`browser/installer/windows/moz.build`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/installer/windows/moz.build#L7

`browser/installer/windows/nsis/defines.nsi.in`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/installer/windows/nsis/defines.nsi.in#L24

Check changes in `browser/installer/windows/` folder for more. (Not sure if it's relevant for us)

`toolkit/mozapps/installer/windows/nsis/common.nsh`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/mozapps/installer/windows/nsis/common.nsh

**Comment by chrmod** [comment]
@sammacbeth was this covered by https://github.com/ghostery/user-agent-desktop/pull/119 ? if so, please close

**Comment by chrmod** [comment]
related https://github.com/ghostery/user-agent-desktop/issues/122

**Comment by sammacbeth** [comment]
* `browser/installer/package-manifest.in`
    1. We just stick with the firefox-named VisualElements Manifest: https://github.com/ghostery/user-agent-desktop/blob/master/brands/ghostery/branding/firefox.VisualElementsManifest.xml
    2. Adult domains are not needed (no auto-forget tab)
    3. Looks like custom prefs maybe. Not needed
 * `browser/installer/windows/Makefile.in`. Looks like some custom branding files. We can ignore.
 * `browser/installer/windows/app.tag`. I don't see where this 'Title' is applied to the installer. From what I can tell from the installer this string is not visible in the metadata you can see with standard windows tools. It's probably ok to leave.
 * `browser/installer/windows/moz.build` - this file looks to be the same as in mozilla source.
 * `browser/installer/windows/nsis/defines.nsi.in` I assume these are defaults that can then be overwritten by the branding config: https://github.com/ghostery/user-agent-desktop/blob/master/brands/ghostery/branding/branding.nsi

My conclusion would be that it looks ok to ignore these changes and close this.
