### ISSUE TITLE
Preferences Settings

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#175]
`browser/locales/en-US/browser/preferences/preferences.ftl`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/browser/preferences/preferences.ftl

**Comment by chrmod** [comment]
@sammacbeth was this covered by https://github.com/ghostery/user-agent-desktop/pull/125 ?

**Comment by sammacbeth** [comment]
Which change does this refer to?

**Comment by chrmod** [comment]
Tracking protection changes https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/browser/preferences/preferences.ftl#L6

**Comment by sammacbeth** [comment]
This setting has not been hidden by #210. Should we reintroduce a DNT option, or leave no preferences options for it?

**Comment by chrmod** [comment]
DNT got deprecated, right? I would not invest in it right now.
