### ISSUE TITLE
Ghostery Branding (Misc)

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#176]
`browser/locales/en-US/chrome/overrides/appstrings.properties` (Customize messages in locales)
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/chrome/overrides/appstrings.properties

Basically I think we need to grep for `Firefox` and `Mozilla` in folder `browser/locales/en-US/chrome/overrides/` and replace with Ghostery. Maybe we can semi-automatically update this folder?
Also `toolkit/locales/en-US`.

**Comment by sammacbeth** [comment]
Perhaps fern can do a preprocessor step to update this file (replace 'Firefox' with `APP_NAME`)?

**Comment by chrmod** [comment]
You mean another custom patch that will go through a list of files and replace all Mozilla/Firefox with Ghostery ? I think that would work well.
