### ISSUE TITLE
DevTools Branding

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#177]
Put Ghostery Logo here?
`devtools/client/themes/images/aboutdebugging-firefox-aurora.svg`
`devtools/client/themes/images/aboutdebugging-firefox-beta.svg`
`devtools/client/themes/images/aboutdebugging-firefox-logo.svg`
`devtools/client/themes/images/aboutdebugging-firefox-nightly.svg`
`devtools/client/themes/images/aboutdebugging-firefox-release.svg`

Update locales:
`devtools/startup/locales/en-US/aboutDevTools.ftl`

**Comment by sammacbeth** [comment]
There are a few issues at present on `about:debugging`:
<img width="607" alt="Screenshot 2020-09-23 at 17 34 07" src="https://user-images.githubusercontent.com/248111/94035117-04d8f980-fdc3-11ea-97ac-f2301fe9c9f4.png">
