### ISSUE TITLE
Disable/Customize Crash Reporter

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#178]
`browser/modules/ContentCrashHandlers.jsm`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/modules/ContentCrashHandlers.jsm#L474

`build/application.ini.in`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/build/application.ini.in#L50

`toolkit/crashreporter/client/crashreporter_osx.mm`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/crashreporter/client/crashreporter_osx.mm#L170

`toolkit/crashreporter/client/crashreporter_win.cpp` (specific to crash reported on Windows)
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/crashreporter/client/crashreporter_win.cpp

**Comment by chrmod** [comment]
For now we should rather disable crashreporter completely.

**Comment by chrmod** [comment]
@sammacbeth  is the crash reporter disabled already? We can close this issue or not yet?
