### ISSUE TITLE
Allow Home Page Customization?

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#179]
Depending on if the customization of home page by user is allowed or not, the following might be relevant:
`browser/modules/HomePage.jsm`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/modules/HomePage.jsm#L17
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/modules/HomePage.jsm#L81
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/modules/HomePage.jsm#L203

`browser/components/extensions/parent/ext-url-overrides.js`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/extensions/parent/ext-url-overrides.js#L77

**Comment by chrmod** [comment]
I would say, why not.
