### ISSUE TITLE
Update Build PGO Server Locations

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#181]
@chrmod Not clear what this is for?
`build/pgo/server-locations.txt`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/build/pgo/server-locations.txt#L133

**Comment by chrmod** [comment]
related https://github.com/ghostery/user-agent-desktop/issues/204

**Comment by sammacbeth** [comment]
I believe this is just for doing a MITM on these domains for tests. See https://searchfox.org/mozilla-central/source/build/pgo/genpgocert.py#72

I think we can ignore this for the purpose of PGO builds.

**Comment by chrmod** [comment]
Good. Closing for now
