### ISSUE TITLE
Package Extra XPI

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#182]
`config/rules.mk`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/config/rules.mk#L915

Not sure if this is still relevant. We used it for Cliqz extension, HTTPs Everywhere, Consentrick, Dat.

**Comment by chrmod** [comment]
We should rather take the same approch we use for Ghostery addon if needed.
