### ISSUE TITLE
Update About Redirectors

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#184]
@chrmod Not sure what this is?
`docshell/base/nsAboutRedirector.cpp`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/docshell/base/nsAboutRedirector.cpp#L92

**Comment by chrmod** [comment]
This is disabling `about:mozilla` page. For reference https://github.com/cliqz-oss/browser-f/commit/5a0e07d53671a646f836e5909efa508de56f52d0

**Comment by chrmod** [comment]
Depending of the usage https://searchfox.org/mozilla-central/search?q=about%3Amozilla&case=true&path= we should rather hide about:mozilla links or replace them with something else.

This needs a decission but is likely low priority as we have not stumbled upon its occurance yet.
