### ISSUE TITLE
Update ipc FunctionHook

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#185]
@chrmod

`dom/plugins/ipc/FunctionHook.cpp`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/dom/plugins/ipc/FunctionHook.cpp#L94

`dom/plugins/ipc/PluginInstanceChild.cpp`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/dom/plugins/ipc/PluginInstanceChild.cpp#L1890

`dom/plugins/ipc/hangui/module.ver`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/dom/plugins/ipc/hangui/module.ver#L1

`ipc/app/module.ver`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/ipc/app/module.ver#L1

**Comment by chrmod** [comment]
related https://github.com/ghostery/user-agent-desktop/issues/191

**Comment by chrmod** [comment]
related https://github.com/ghostery/user-agent-desktop/issues/197

**Comment by sammacbeth** [comment]
The `module.ver` files seem to affect the .exe metadata. This currently looks OK, except Copyright and Legal should be updated.

<img width="301" alt="Screenshot 2020-09-23 094637" src="https://user-images.githubusercontent.com/248111/93982652-c5d68400-fd81-11ea-9f1e-61fdb8ab90c0.png">

**Comment by sammacbeth** [comment]
Fixed in #247
