### ISSUE TITLE
Disable Abuse Reports

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#186]
@chrmod

`modules/libpref/init/all.js`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/modules/libpref/init/all.js#L2354 (default: true)
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/modules/libpref/init/all.js#L2357 (default: true)

**Comment by sammacbeth** [comment]
This refers to the extension Report mechanism on `about:addons`.

<img width="661" alt="Screenshot 2020-09-23 at 17 30 54" src="https://user-images.githubusercontent.com/248111/94034745-a4e25300-fdc2-11ea-8d47-d216402f4d51.png">

I think we should disable this as the following page says the report will go to us, but it will be submitted to Mozilla.
<img width="421" alt="Screenshot 2020-09-23 at 17 32 03" src="https://user-images.githubusercontent.com/248111/94034876-c80d0280-fdc2-11ea-9568-9054a39cb5c2.png">

**Comment by chrmod** [comment]
If this require more than a pref change I would suggest to move it to next iteration.
