### ISSUE TITLE
Decide on default and additional search engines list

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#19]
Related change:

- [ ] https://github.com/human-web/user-agent-desktop/pull/6/files#diff-66ac8ac194664d878e5bcd3612ab0ef8R93-R127

**Comment by sammacbeth** [comment]
Note that search engine configuration has been migrated to remote settings so in future firefox builds the `lists.json` file no longer exists and it may be trickier to configure our own default search. https://bugzilla.mozilla.org/show_bug.cgi?id=1542269

**Comment by chrmod** [comment]
This will be covered by upcoming Search Engine Choice Screen issue

**Comment by chrmod** [comment]
Also was partially covered by https://github.com/ghostery/user-agent-desktop/pull/249
