### ISSUE TITLE
Tweak Trust Domains Certificates

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#190]
Not sure if this is needed?

`security/apps/AppTrustDomain.cpp`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/security/apps/AppTrustDomain.cpp#L61

`security/apps/gen_cert_header.py`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/security/apps/gen_cert_header.py#L36

`security/apps/moz.build`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/security/apps/moz.build#L46

`security/manager/ssl/nsIX509CertDB.idl`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/security/manager/ssl/nsIX509CertDB.idl#L252

**Comment by chrmod** [comment]
There should be no reason we would need to sign our own addons. Closing for now
