### ISSUE TITLE
Tweak Windows Register?

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#191]
`toolkit/components/extensions/NativeManifests.jsm`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/components/extensions/NativeManifests.jsm#L34

**Comment by chrmod** [comment]
This is likely very important. Question, why it is hardcoded and does not use AppInfo vendor instead?

**Comment by sammacbeth** [comment]
> This is likely very important. Question, why it is hardcoded and does not use AppInfo vendor instead?

This looks like it's for extension native-messaging. On windows a [registry entry](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#Registry) is used to location the binary the browser needs to launch for a specific extension. By _not_ changing this, we will get automatic compat with any extension that uses this, as applications will set the registry key with a Firefox prefix.

**Comment by chrmod** [comment]
Make sense
