### ISSUE TITLE
Check if addons should be allowed to change theme

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#192]
`toolkit/components/extensions/parent/ext-theme.js`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/components/extensions/parent/ext-theme.js#L456
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/components/extensions/parent/ext-theme.js#L473

**Comment by chrmod** [comment]
I would say, why not.
