### ISSUE TITLE
Looks like Firefox when loading Mozilla's webpages

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#193]
@chrmod?
`toolkit/components/urlformatter/URLFormatter.jsm`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/components/urlformatter/URLFormatter.jsm#L120

**Comment by chrmod** [comment]
Was trying to figure out what exactly this change was meant to do, but cannot find any good explanation.

**Comment by chrmod** [comment]
Looks like this allow rebranded browsers to install addons from AMO. So is in fact critical to have.

**Comment by sammacbeth** [comment]
I tested that fix and it didn't work for me. I'm currently looking into the code for addons.mozilla.org to see how they UA detection to control how the install button is displayed. Relevant issue there: https://github.com/mozilla/addons-frontend/issues/4910

**Comment by sammacbeth** [comment]
Fixed with UA spoofing in #229
