### ISSUE TITLE
Make sure system addon is not blocklisted

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#195]
@chrmod not sure if this is needed?
`toolkit/mozapps/extensions/Blocklist.jsm`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/mozapps/extensions/Blocklist.jsm#L1238

**Comment by chrmod** [comment]
This seems to be some weird edge case. As I understand the check was meant to prevent situation in which Firefox remote addon would blacklist the system addon. IMHO the proper approch is to disable such remote updates from Mozilla in first place. 

Let's discard this change.
