### ISSUE TITLE
Disable Addon recommendations?

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#196]
`toolkit/mozapps/extensions/content/aboutaddons.html`
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/mozapps/extensions/content/aboutaddons.html#L38

Cliqz used to have its own recommended addon-ons list: https://cliqztix.atlassian.net/browse/DB-2193
Commit: https://github.com/cliqz-oss/browser-f/commit/72b393692b527d57a0b85e7887efeef5c241cfa4

`toolkit/mozapps/extensions/content/aboutaddons.js` https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/mozapps/extensions/content/aboutaddons.js#L113

`toolkit/mozapps/extensions/internal/XPIInstall.jsm` (Allow addons signed with Cliqz certs as well?)
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/toolkit/mozapps/extensions/internal/XPIInstall.jsm#L261

**Comment by chrmod** [comment]
If possible it would be best to avoid signing addons with new cert. In UA approach we can ship addons as system adddons together with the browser so in that way we don't have to sign them individually.

When it comes to recommended addons, that's a feature and we should consider it only when there will be a good reason to implement it.

Closing for now.

**Comment by sammacbeth** [comment]
I think this also refers to the 'Recommended Addons' section shown on `about:addons`:

<img width="771" alt="Screenshot 2020-09-14 at 16 56 40" src="https://user-images.githubusercontent.com/248111/93102082-61456600-f6ab-11ea-802d-f3a6f1010397.png">

**Comment by chrmod** [comment]
ok, now I got it. Sorry for confusing two things.

@tillhouse as we think about having own recommended addons list I would say we should either:
1. hide Firefox list
2. replace recommendation list by our own

**Comment by chrmod** [comment]
Based on #118 we can set `pref("extensions.htmlaboutaddons.recommendations.enabled", false); ` to disable recommendations

**Comment by chrmod** [comment]
related https://github.com/ghostery/user-agent-desktop/issues/208
