### ISSUE TITLE
Network analysis

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#198]

**Comment by sammacbeth** [comment]
Connections made on browser startup:
 * `detectportal.firefox.com` - for internet connectivity test.
 * `location.services.mozilla.com/v1/country?key=no-mozilla-api-key` - cc #187 
 * `firefox.settings.services.mozilla.com` (https://remote-settings.readthedocs.io)
 * `push.services.mozilla.com` - #137 
 * `content-signature-2.cdn.mozilla.net`
 * `tracking-protection.cdn.mozilla.net`
 *  `firefox-settings-attachments.cdn.mozilla.net`
 * `snippets.cdn.mozilla.net` - Messages for new tab page #132 
 * `redirector.gvt1.com` - Widevine download
 * `normandy.cdn.mozilla.net`
 * `classify-client.services.mozilla.com`

**Comment by chrmod** [comment]
Pushing it to next milestone

**Comment by sammacbeth** [comment]
`detectportal.firefox.com` has now been replaced by #326

**Comment by sammacbeth** [comment]
These are now all either obsolete, or covered by separate issues.
