### ISSUE TITLE
Remove Data Collection and Use from preferences

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/user-agent-desktop#201]
`about:preferences#privacy`:
<img width="652" alt="Screenshot 2020-09-14 at 17 09 20" src="https://user-images.githubusercontent.com/248111/93103577-1b899d00-f6ad-11ea-92f0-e1cc61da3a2d.png">

We are not using any of these settings. I suggest we remove this whole preferences section.

**Comment by chrmod** [comment]
We should most importantly be sure that non of the Firefox data collection is enabled. Prefs resposibe for enabling those futures should be locked and endpoints replaced with ghostery domain names (even if not used at this point).

**Comment by sammacbeth** [comment]
Closed by #217
