### ISSUE TITLE
Help and support pages

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/user-agent-desktop#202]
Firefox help and support links are littered around the browser. Some prominent examples:
 * 'Help' section from the right burger menu. Links all go to firefox support
<img width="292" alt="Screenshot 2020-09-14 at 17 32 28" src="https://user-images.githubusercontent.com/248111/93106310-68bb3e00-f6b0-11ea-82a8-913f7e096c3b.png">
 * 'Learn more' links in preferences.
<img width="434" alt="Screenshot 2020-09-14 at 17 34 13" src="https://user-images.githubusercontent.com/248111/93106462-9607ec00-f6b0-11ea-96c5-7442c305f3da.png">

Should we remove these occurrences. Should some be routed to Ghostery support?

**Comment by chrmod** [comment]
As for now I would recommend to hide "Learn more" links and those menu items that we cannot provide a proper website for.
