### ISSUE TITLE
Optimized builds

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#204]
To achieve best performance we should enable PGO for release builds.

**Comment by chrmod** [comment]
Take a look on `MOZ_PGO`

**Comment by remusao** [comment]
Maybe this would be useful to look at: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/firefox#n108

**Comment by sammacbeth** [comment]
Implemented by #321
