### ISSUE TITLE
Ghostery Default Bookmarks

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#232]
We should change, rename, or eliminate the default FF bookmarks to match our own preferred options.

**ACCEPTANCE CRITERIA:**

These bookmarks should have the following links:

Help and Tutorials
- Rename:  Help
- Link:  https://www.ghostery.com/support/

Customize Firefox
- Eliminate

Get Involved
- Rename:  Ghostery Plans
- Link:  https://www.ghostery.com/pricing/

About Us
- Link: https://www.ghostery.com/about-ghostery/

**Comment by sammacbeth** [comment]
Duplicate of #200
