### ISSUE TITLE
Browser Options - Home Cleanup

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#233]
In the Options settings (about:preferences), there are a number of changes we need to make to the Home section. 

**ACCEPTANCE CRITERIA**
_Home_
- Remove "Firefox Home" as a new tab option
- Give the user the option to set their own URL for the new tab.
- Remove Firefox Home Content

**Comment by chrmod** [comment]
@tillhouse there is no way to let users choose their own new tab page. This is long discussed (by Firefox) security issue. Only addons can make the change.

**Comment by chrmod** [comment]
Closing in favor of https://github.com/ghostery/user-agent-desktop/issues/60
