### ISSUE TITLE
Windows installer feedback text

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/user-agent-desktop#238]
When uninstalling on Windows there is a checkbox on the final page: "Tell Mozilla why you uninstalled Ghostery" (defined [here](https://searchfox.org/mozilla-central/source/browser/locales/en-US/installer/custom.properties#76))

If checked, the user is sent to a survey URL after completing the uninstall. This URL is specified [here](https://searchfox.org/mozilla-central/source/browser/installer/windows/nsis/uninstaller.nsi#143).

We could update this to point to the existing Ghostery offboarding, or create a new offboarding survey.

**Comment by tillhouse** [comment]
Hey @sammacbeth, change the link to this:

- https://www.surveymonkey.com/r/6LHDV6Y

**Comment by fcjr** [comment]
@tillhouse From the extension we typically link to `https://ghostery.com/uninstall` to avoid having to change anything in the extension if we want to change or update the survey we probably want to do this here as well however the `uninstall` link sends you to https://www.surveymonkey.com/r/2BSXDNR (which looks identical to the one you linked but has a different ID, can you take a look and confirm which one we should be linking to?

**Comment by sammacbeth** [comment]
Fixed in latest nightly.
