### ISSUE TITLE
Help links need to be changed

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#244]
In the Help section of the Options menu (the one that drops down when you click on the three-line icon) the links all point to Mozilla website and need to be redirected to Ghostery sites or eliminated. 

**ACCEPTANCE CRITERIA:**

"Ghostery Help" 
- this should link to https://www.ghostery.com/support/

"Ghostery Tour" 
- this link should be eliminated

"Keyboard shortcuts" 
- this should redirect to a Ghostery FAQ link (TBD)

"Submit feedback"
- this should link to https://www.ghostery.com/support/

 "About Ghostery" link
- update "Licensing Information", "End-User Rights" and "Privacy Policy" to Ghostery links

**Comment by tillhouse** [comment]
I'm working with Pete to get the exact links we want here.

**Comment by sammacbeth** [comment]
This is partially done

 - [x] "Ghostery Help" link updated
 - [x] "Ghostery Tour" removed
 - [ ] "Keyboard Shortcuts" goes to a redirect link that we can update as needed.
 - [x] "Submit feedback" link updated
 - [ ] "Licensing Information" we can update the internal page, see #56
 - [ ] "End-User-Rights" is also an internal page, see #57
 - [ ] "Privacy Policy" goes to https://www.ghostery.com/about-ghostery/privacy-statements/

**Comment by chrmod** [comment]
As those links that are not covered already have their dedicated issues it is fine to close this one for now.
