### ISSUE TITLE
Ghostery Browser not listed among default choices

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#245]
When I try to set Ghostery Browser as my default browser, I don’t see it listed among the choices. 

ENVIRONMENT:

Windows 10

IMAGES:
![image](https://user-images.githubusercontent.com/1709237/93954337-752c4000-fd1b-11ea-8ed7-64f5869fcfd8.png)
![image](https://user-images.githubusercontent.com/1709237/93954356-82e1c580-fd1b-11ea-9859-ed7cfb8a3a66.png)

**Comment by sammacbeth** [comment]
This works for me. Maybe try reinstalling?
<img width="350" alt="Screenshot 2020-09-23 092608" src="https://user-images.githubusercontent.com/248111/93980425-e7823c00-fd7e-11ea-9332-096a8ca68008.png">

**Comment by chrmod** [comment]
It works fine for me.

**Comment by tillhouse** [comment]
It's working for me now.
