### ISSUE TITLE
Windows signing key not recognised by Windows

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/user-agent-desktop#246]
When running the latest installer:

<img width="398" alt="Screenshot 2020-09-23 092045" src="https://user-images.githubusercontent.com/248111/93980069-6f1b7b00-fd7e-11ea-843c-f37c8708127b.png">

**Comment by chrmod** [comment]
Looks like all is fine and the app has to build some reputation to prevent this screen from popping up. 

More info:
https://www.digicert.com/blog/ms-smartscreen-application-reputation/
https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview
