### ISSUE TITLE
Remove 'Recommended Addon' icon

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/user-agent-desktop#256]
On `about:addons` the Firefox recommended addon is shown for some addons.

![Screenshot 2020-09-25 160617](https://user-images.githubusercontent.com/248111/94283921-91adbf80-ff49-11ea-8b71-d287f58cebc0.png)

**Comment by chrmod** [comment]
How did you manage to get to see it? Haven't we disabled addon recommendation already?

**Comment by sammacbeth** [comment]
> 
> 
> How did you manage to get to see it? Haven't we disabled addon recommendation already?

Install the firefox multi-account containers addon. That's where I saw it.
