### ISSUE TITLE
Hide 'Learn More' link in addon settings

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/user-agent-desktop#257]
On `about:addons` there is a Learn more link under the run in private window settings.

![Screenshot 2020-09-25 160725](https://user-images.githubusercontent.com/248111/94283950-9ffbdb80-ff49-11ea-8236-dbaa5f8f6886.png)

**Comment by chrmod** [comment]
Must have been fixed by https://github.com/ghostery/user-agent-desktop/pull/243
