### ISSUE TITLE
HTTPS everywhere

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#26]
Edit: might be relevant: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-941d3914009927fd280a4abd6b8a9d5aR1393

**Comment by 2br-2b** [comment]
Now that Firefox will basically have this built-in, should we close this and #153?

**Comment by sammacbeth** [comment]
Yes, now with #367 I think we don't need HTTPS everywhere.
