### ISSUE TITLE
Uninstall Survey

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#260]
As a Ghostery UX researcher, when a user uninstalls the product I would like them to have the option to take a survey so that we can better understand why they are not using the product.

**ACCEPTANCE CRITERIA:**

- On uninstall, the user should have the option to take a survey at this link: https://www.surveymonkey.com/r/6LHDV6Y

**Comment by chrmod** [comment]
Few notes:
* on windows this can be easily done https://searchfox.org/mozilla-central/source/browser/installer/windows/nsis/uninstaller.nsi#143
* on macos there is no uninstalling concept so we cannot show the survey
* there already is a patch customizing the survey url https://github.com/ghostery/user-agent-desktop/blob/823ca8b46d6f4194dd21ffef26971f476553bb90/patches/0017-Update-uninstaller-survey-URL.patch

**Comment by chrmod** [comment]
@tillhouse should this be implemented in public beta or for first release?

**Comment by sammacbeth** [comment]
This was already implemented by the patch mentioned and https://github.com/ghostery/user-agents/blob/101579265dbcfb5ce847ad6008baf8270d5fb4ed/deploy/userdata.sh.tmpl#L15-L17

**Comment by tillhouse** [comment]
If we can have this live in the public beta, that would be good.  Is it correct to say that this cannot be done for MacOS?  If not, we can do it for Windows only.

**Comment by sammacbeth** [comment]
@tillhouse this should be already live on the current nightly. It is not possible on Mac.
