### ISSUE TITLE
URL Text Not Highlighted (Windows)

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#266]
For the Ghostery themes on Windows, when you highlight the text in the URL bar, it doesn't work.  The text changes color from black to blue but the background stays white, making it hard to confirm that you've selected the text:

![image](https://user-images.githubusercontent.com/1709237/94706757-9939e380-0310-11eb-9396-f7f00f154e13.png)

This is what it should look like:
![image](https://user-images.githubusercontent.com/1709237/94706978-e1f19c80-0310-11eb-844c-3dcb44261234.png)

**Comment by chrmod** [comment]
should be done together with https://github.com/ghostery/user-agent-desktop/issues/267
