### ISSUE TITLE
Update "Secure Page" Logo to something other than the Ghostery Logo

### ISSUE THREAD

**Issue by fcjr** [ghostery/user-agent-desktop#269]
Can be confusing to users now that we've moved the extension icon into the URL bar.

<img width="372" alt="Screen Shot 2020-10-01 at 2 37 34 PM" src="https://user-images.githubusercontent.com/2053002/94850924-a7156480-03f5-11eb-88ba-22cc3bb32dde.png">

**Comment by vincentlai88** [comment]
Here are some lock icons to replace the Ghosty so it's less confusing. There are 2 lock icons to still represent secure. One is pretty normal and the other has a Ghosty in it. I think probably the normal one is better since it will be too small to see the tiny ghosty in that one. Thanks!
[lock icons.zip](https://github.com/ghostery/user-agent-desktop/files/5337472/lock.icons.zip)

**Comment by chrmod** [comment]
@vincentlai88 thank for the icons. Unfortunately I don't think they solve the problem as "second" ghostery icon is being shown as a branding element for internal pages while the "first" one is regular addon icon. 

Secure connection icon that comes from Firefox looks just fine on regular websites.
<img width="161" alt="Screenshot 2020-10-08 at 12 29 19" src="https://user-images.githubusercontent.com/1228153/95447369-e564d380-0961-11eb-9a1f-2b85b42fd5d2.png">

IMAO we don't have to do anything about this issue anytime soon as very little users see those internal pages and even if they see it, the confusion created by double logo should not impact the product significantly. 

What do you think @tillhouse @vincentlai88 ?

**Comment by vincentlai88** [comment]
Ah I see, yes then the lock icons I sent over won't work. I must have interpreted it wrong, I actually thought we needed a secure page logo. But now I know we need a Ghostery logo that is not Ghosty. That is tough. Though I am working on logo items for search and the browser and they might work. It's in progress and I'll drop it here when they are ready. Thanks!

**Comment by Melissa-Kay** [comment]
I was pretty confused about the icon on the left as I thought that something was wrong not finding the icon on the right. Brave has their icon in the URL bar but to the right. My vote is we should keep positioning consistent as users will likely default to that area to view stats.

![Screen Shot 2020-10-08 at 3 27 56 PM](https://user-images.githubusercontent.com/3027874/95511150-0f7bbd00-0985-11eb-89e1-4c2305f7f370.png)

**Comment by chrmod** [comment]
Some counter examples for positioning tracking protection icon:
Safari
<img width="608" alt="Screenshot 2020-10-09 at 10 10 22" src="https://user-images.githubusercontent.com/1228153/95559180-a5f8be80-0a17-11eb-90ab-706de3532530.png">

Firefox
<img width="265" alt="Screenshot 2020-10-09 at 10 12 06" src="https://user-images.githubusercontent.com/1228153/95559359-e5bfa600-0a17-11eb-9e17-4dbf1fa6b75f.png">

Also Ghostery mobile for iOS and Android both position tracking protection on the right of urlbar.

It's a matter of preference it seems. Both positions should work for users as they will get used to them eventually.

**Comment by Melissa-Kay** [comment]
But it sounds like keeping it i the URL bar but moving it to the right solves the double ghosty issue? I had a look at FF. When I go to user preferences, I get this... with no blocking/stat counter. 

![Screen Shot 2020-10-09 at 10 41 39 AM](https://user-images.githubusercontent.com/3027874/95597001-186b9d80-0a1c-11eb-9924-e31f5f9ee225.png)

If we could do something similar, that could also solve it.

**Comment by chrmod** [comment]
That's a perfectly valid point and honestly, time vise it is probably cheaper to move it to the right even if my personal preference is to keep it on the left.

@vincentlai88 @alexei-cliqz this is a crucial decision as it comes for brand identification, what do you think?

**Comment by alexei-cliqz** [comment]
Hey there, proposals I see from you guys look reasonable. I think ghosty icon will work fine as long inside URL bar. I also like monochrome Firefox example from Melissa above.

**Comment by vincentlai88** [comment]
Hi
I understand the approach to moving it to the left of the url bar, I played around with a few options of using a different logo that may work, but the ghosty logo is the best option, therefore there's no good solution for that that I've attempted. I also agree that moving it to the right will help eliminate the confusion. In terms of branding identification, I don't think moving it to the right will be an issue.

**Comment by chrmod** [comment]
> If we could do something similar, that could also solve it.

This would in be best, but I cannot see how to implement it fast right now.

IMAO Ghostery on the left looks much better than one on the right - also because on the right there may be more addon icons (so called page action buttons) and then the branding gets diluted. Double Ghosty does not happen very often, so I don't think we should touch this topic right now.

**Comment by fcjr** [comment]
figure we can close this now that Dawn has its own logo =)
![Screen Shot 2021-01-20 at 10 50 02 AM](https://user-images.githubusercontent.com/2053002/105200068-6e68da80-5b0d-11eb-9b07-480196c719c3.png)

**Comment by chrmod** [comment]
A happy ending :D
