### ISSUE TITLE
macOS installer DMG is not sized properly

### ISSUE THREAD

**Issue by fcjr** [ghostery/user-agent-desktop#270]
It should be sized to the background image, however currently it is much larger
<img width="928" alt="Screen Shot 2020-10-01 at 3 13 30 PM" src="https://user-images.githubusercontent.com/2053002/94868784-d934bf80-0411-11eb-9b01-b0057124a4c1.png">

**Comment by sammacbeth** [comment]
We are currently using [node-appdmg](https://github.com/LinusU/node-appdmg) to create the styled DMG, using the config specified here: https://github.com/ghostery/user-agent-desktop/blob/master/ci/Ghostery-dmg.json

As the background image seems to just be a single colour, perhaps we could just use the `background-color` option to fill the entire area?

**Comment by chrmod** [comment]
Let's try the simplest solution that does not look broken.

**Comment by fcjr** [comment]
@sammacbeth node-appdmg has window size options I have opened pr #282 to fix this issue.
