### ISSUE TITLE
Need Padding in around Ghostery Icon

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#271]
Since the ghosty is moved into the url bar in the Ghostery Browser, the counter for it sits a bit high and touches the top of the bar. It looks a bit uncomfortable. 

**Possible solutions:**
- move counter to the bottom of the icon
- create more padding with the URL bar
- shift the icon down slightly

![image](https://user-images.githubusercontent.com/1709237/94879759-296e4a80-042f-11eb-8590-f33296aaca4e.png)

**Comment by chrmod** [comment]
@vincentlai88 can you please take a look? We need a design before starting to work on this one. cc @tillhouse

**Comment by vincentlai88** [comment]
Chris mention you can't change the location of the counter so I wonder if we can just move the ghosty 2 pixels down?

**Comment by tillhouse** [comment]
@chrmod how detailed of a design do you need?  i could address this in the new privacy hub design vinny put together (screenshot below)

![image](https://user-images.githubusercontent.com/1709237/96068066-13b64780-0e69-11eb-96c6-76d530a71e8e.png)

**Comment by chrmod** [comment]
On this screenshot the "padding" was achieved by moving the "number box" few pixels down.  Is it something we want to do for all addons or only for Ghostery ones? 

Adding the padding by increasing the space around the icon may be very hard/impossible as it would change the height of the urlbar. Such change is definitely possible but it should be a part of a holistic UI redesign as urlbar is a key element of browsers UI.

But if we want to move the box down a bit for all addons this is very cheap.

**Comment by vincentlai88** [comment]
Yea I think moving the counter box itself lower on the icon is the best and quickest. I'm glad that's an option.

**Comment by chrmod** [comment]
Implemented by https://github.com/ghostery/user-agent-desktop/pull/293
