### ISSUE TITLE
MacOS - Disk Icon Improvements

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#272]
**PROBLEM**
Currently on Mac the disk image icon is a Ghosty in a cardboard box. This is a problem because it doesn’t look anything like most disk images (which generally have some form of disk icon) and it looks more like a package installer (.pkg, which generally have a cardboard box icon). This may confuse mac users. 
![image](https://user-images.githubusercontent.com/1709237/94880400-d1d0de80-0430-11eb-8888-281807ea202c.png)

**PROPOSED SOLUTION:**
This icon would make more sense to Mac users:
![image](https://user-images.githubusercontent.com/1709237/94880458-fdec5f80-0430-11eb-9b99-169a9525190e.png)

**Comment by fcjr** [comment]
In icns format: 
[GhosteryBrowserDiskImage.icns.zip](https://github.com/ghostery/user-agent-desktop/files/5315734/GhosteryBrowserDiskImage.icns.zip)
