### ISSUE TITLE
Enterprise Roots warning still mentions Mozilla

### ISSUE THREAD

**Issue by fcjr** [ghostery/user-agent-desktop#275]
<img width="1115" alt="Screen Shot 2020-10-06 at 6 25 12 PM" src="https://user-images.githubusercontent.com/2053002/95266529-5c368b00-0801-11eb-9176-74253c7b150a.png">

**Comment by sammacbeth** [comment]
I guess we should also have a separate ticket to not show this warning for the Ghostery cert?

**Comment by sammacbeth** [comment]
The 'learn more' link goes to the `enterprise-roots` slug - we should add a redirect for that.

**Comment by chrmod** [comment]
@sammacbeth can you add an issue to replace `enterprise-roots` slug?
