### ISSUE TITLE
Search Bar missing "with <Search Provider>" until first user input

### ISSUE THREAD

**Issue by fcjr** [ghostery/user-agent-desktop#294]
When a new tab opens the search bar states `Search or enter address` and does not state what search provider will be used until first user input, on new windows the search bar should state what search provider the search will be made with for example `Search with DuckDuckGo or enter address`

Note on vanilla Firefox the `with <Search Provider>` text appears as soon as you open a window.

![search(2)](https://user-images.githubusercontent.com/2053002/96324932-4b9cc680-0ff2-11eb-8228-9c9e4433e162.gif)

**Comment by chrmod** [comment]
`Search with ...` is a new feature of Firefox. As we've just synced with Firefox 82 it will now be available in Ghostery browser. https://github.com/ghostery/user-agent-desktop/pull/290
