### ISSUE TITLE
Firefox Reference in Application Prompt

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#300]
When you are prompted to open a link in a specific application, like Zoom, there is a reference to Firefox when you are asked to save your preference (see below)

ENVIRONMENT:
- Windows 10
- Ghostery Browser v

REPRO STEPS:
* Click on a Zoom link to start a Zoom meeting

SCREENSHOTS:
![application open link preference](https://user-images.githubusercontent.com/1709237/96593845-f5f94000-12b7-11eb-947d-f5eff0aba0ef.png)

**Comment by sammacbeth** [comment]
This should be fixed in the lastest version. Can you check against and confirm? On my device Ghostery is shown in the text.
