### ISSUE TITLE
Logo Missing from About Ghostery Pop-Up

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#348]
The "About Ghostery" pop-up is often missing the Ghostery logo.  Let's change the logo and the word mark to prevent this from happening and to align with the Ghostery brand.

ACCEPTANCE CRITERIA:
* Use the Icon file for the Ghostery icon
* Use the Ghostery Browser word mark in place of the current "Ghostery Browser" text (see image below):
![image (10)](https://user-images.githubusercontent.com/1709237/99088202-bd3c4600-2599-11eb-9c37-8d6e5f22dd83.png)

DESIGN SPECS & ASSETS: 
[ghosty_cBk_icon.zip](https://github.com/ghostery/user-agent-desktop/files/5537694/ghosty_cBk_icon.zip)
![ghostery browser word mark](https://user-images.githubusercontent.com/1709237/99088231-c7f6db00-2599-11eb-92aa-e05cbcb5708f.png)

**Comment by chrmod** [comment]
closing in favor of https://github.com/ghostery/user-agent-desktop/issues/451
