### ISSUE TITLE
Remove Google Safe Browsing

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#38]
Old ticket: https://cliqztix.atlassian.net/browse/DB-2442
Link to diff: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-9245bfedc150b2bf3b0c200881916ff8R87-R89

This might require us to provide a new endpoint like here: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-9245bfedc150b2bf3b0c200881916ff8R120

**Comment by 2br-2b** [comment]
I wonder if something like https://the8-bit.com/apple-proxies-google-safe-browsing-privacy/ is possible. Apple probably won't release their proxy publicly, but if they do, we could use that.

It may not be feasible for Ghostery to host their own proxy, but I just thought I'd put this on the table.

**Comment by yokoffing** [comment]
Prefs related to this: https://github.com/ghostery/user-agent-desktop/blob/19706e3396cf9a3eea8255ef98409bf4602eeddf/brands/ghostery/branding/pref/firefox-branding.js#L156-L157 and #379.

***

Brave found a way to proxy SafeBrowsing requests and Geolocation requests. "Google does not receive any information about which client is performing these requests (not even your IP address)." See [here](https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)#services-we-proxy-through-brave-servers).

[NextDNS](https://nextdns.io/) also tinkers with Google Safe Browsing to be privacy-persevering.

![Screenshot 2021-02-11 at 3 37 52 PM](https://user-images.githubusercontent.com/11689349/107696360-d8dde800-6c7f-11eb-9882-cccc8d2065c5.jpg)

***

If Ghostery can still use CLIQZ anti-phishing technology _and_ remove a call to Google, I'm for it 1000%.

**Comment by chrmod** [comment]
Cliqz anti-phishing technology is sadly no longer maintained.

**Comment by chrmod** [comment]
Google Safe Browsing is a defacto standard and we definitely should use it to protect our users. Ideally we do that via proxy server same as Apple/Brave does it. 

I'm closing this issue in favor of https://github.com/ghostery/user-agent-desktop/issues/509 and https://github.com/ghostery/user-agent-desktop/issues/510
