### ISSUE TITLE
Add option for unpacked extensions

### ISSUE THREAD

**Issue by 2br-2b** [ghostery/user-agent-desktop#384]
This is something Firefox removed that would be extremely useful for me as a dev. I would like it if I could specify a folder and have it automatically load the extension files from there. It's much more convenient than repackaging the extension I'm actively working on over and over when testing it on a day-to-day basis.

Another way to implement this would be to make a way to automatically load a list of temporary extensions when the program loads.

**Comment by 2br-2b** [comment]
This and Mozilla's inclusion of Pocket, a proprietary service, in Firefox are pretty much the only thing keeping me using a chromium-based browser (Brave) rather than a Firefox-based one. Having this would knock out both of those hurdles!

**Comment by chrmod** [comment]
Being an extension developer myself I've solved that issue by adopting [web-ext](https://github.com/mozilla/web-ext). We are using it also as a part of dev setup of Ghostery Search Extension - take a look https://github.com/ghostery/ghostery-search-extension/blob/aeeb64649dbc2c949a0abb74b34c3e39643bd970/package.json#L8. One huge benefit of web-ext in contrast to loading unpacked addons is that the extension reload on every code change. Please let us know if that helps.

**Comment by 2br-2b** [comment]
From looking at the docs, does this support multiple extensions? It seems you can only load one extension at a time using web-ext, and the issue for enabling support for multiple extensions (https://github.com/mozilla/web-ext/issues/1107) hasn't been updated since January.

**Comment by chrmod** [comment]
web-ext is a development tool so it focuses on a single addon. Maybe you can try use multiple web-ext connected to same browser?

Regarding loading of unpacked addons: mozilla decided to disable those as they posed a serious security/privacy threat. Imagine, any application with filesystem access was able to add own unpacked addons and user will likely never notice. That is also why Firefox now require all addons to be signed. 

BTW. You may try to check Firefox developer edition/Nightly and change `xpinstall.signatures.required` to `false`. On those release channels you can load unsigned addons, and perhaps they can load from filesystem. 

You as a developer may try to add your own  unsigned addons into browser installation folder into the path `browser/features`. Let me know if that works.

**Comment by 2br-2b** [comment]
I already have packaged and added some unsigned extensions.

I see why this isn't supported, but it would still be cool to have an advanced option (maybe in about:config) for devs like me. I realize, though, that this is a pretty niche feature, as there are other workarounds to do the same thing (namely, repackaging my extensions after editing them) - I just wish there was an easier way, like there is in Chromuim.

I don't know if there's a way to run multiple web-ext for the same browser at the same time.

**Comment by sammacbeth** [comment]
One possibility would be to unset `MOZ_REQUIRE_SIGNING` in our build configs.
https://github.com/ghostery/user-agent-desktop/blob/36e1325feae78866b35a526ec7e421622510aada/build/configs/macosx.mozconfig#L9

With this off, the browser differs to the `xpinstall.signatures.required` when deciding if a signature is required to install an addon (see https://searchfox.org/mozilla-central/source/browser/components/BrowserGlue.jsm#2318-2324). This would allow you to 'Install Addon from file' in `about:addons` with unsigned addons.

**Comment by chrmod** [comment]
As much as I sympathize with developers needs I also believe that security of all users is a priority. Dealing with such advanced developer use cases of should happen on the upstream side (Mozilla Firefox). We do appreciate the comment @2br-2b but in this case there is little we can do considering our limited resources. Closing for now.
