### ISSUE TITLE
Remove version number from update request

### ISSUE THREAD

**Issue by 2br-2b** [ghostery/user-agent-desktop#386]
When checking for updates, we check at the url `https://get.ghosterybrowser.com/shavar/downloads?client=SAFEBROWSING_ID&appver=%MAJOR_VERSION%&pver=2.2`. To better protect users' privacy, would it be possible to modify both the client and the server so that the version number is not sent, or is that beyond the scope of the project right now?

There could be two ways to handle this:
1. Have 2 server requests: 1 checks the most recent version, if it isn't the most recent, it grabs the changes;
2. Grab the changes, check the version, if the current version is correct, discard them.

1 would probably be the most efficient.

**Comment by sammacbeth** [comment]
I think we could simply drop the version in this call with no negative consequences. We can just update the URL in the pref to remove the `appver` param.

**Comment by chrmod** [comment]
Alright. Seems like an easy change. Lets do it next iteration.

Thanks for suggestion @2br-2b
