### ISSUE TITLE
Replace Firefox with new name throughout the code base

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#39]
Examples of places:
* https://github.com/human-web/user-agent-desktop/pull/6/files#diff-c339ecd920609b37a2bcfe5dc46f0cddR121
* https://github.com/human-web/user-agent-desktop/pull/6/files#diff-3cc3daf8f001c0dbc6e0b45210977b6bR1

In some cases, it might be possible to replace hard-coded values with env variable, which would make it easier to rebrand the browser.

Question @chrmod maybe this one was related to `about:cliqz`? Can you confirm that we do not need that: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-c1256651c0fbbf45fbf7fd55eb379380R60

**Comment by chrmod** [comment]
Covered by other issues already.

Related: https://github.com/ghostery/user-agent-desktop/issues/165
