### ISSUE TITLE
about:home seems to be broken

### ISSUE THREAD

**Issue by 2br-2b** [ghostery/user-agent-desktop#393]
I'm sorry for opening so many issues on this project in such a short period of time, but I found another small issue!

Going to about:home shows the following:

![screenshot](https://user-images.githubusercontent.com/43968991/100559804-dfb0ad80-3281-11eb-8015-29ea7e709fff.png)

Maybe, instead of showing this page, we should automatically redirect about:home to about:newtab, which seems to be the page opened on any new window being opened.

**Comment by chrmod** [comment]
@2br-2b please don't hesitate to open issues. Your feedback is welcomed and very appreciated. 

This is definitely a bug and should get fixed. Must be related to the way we replace home page url.

**Comment by 2br-2b** [comment]
`about:home` now redirects to https://ghostery.com/. Since this bug is fixed, should I go ahead and close the issue?

**Comment by chrmod** [comment]
There are still quite some issues with the home page and new tab page setting. But at least this seems to be better now. 
Ideally about:home would be the same as about:newtab and the same as actual new tab page, but showing ghostery.com is not that bad.

Thank you for looking into it!
