### ISSUE TITLE
File Corrupt Warning for Windows 10

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#397]
Some Windows users are getting a "corrupt file" warning when they try to install the browsers. 

**REPRO STEPS:**
- click windows install link > save > "corrupt file" msg displays

**Comment by sammacbeth** [comment]
This is likely either an issue downloading the file, or caused by modifications to the .exe done by anti-virus programs. Perhaps the user could try the new stub installer instead?

**Comment by chrmod** [comment]
Cannot reproduce this. Please reopen if we will get more reports of this happening.
