### ISSUE TITLE
HTTPS-Only Mode - Catching Sites Already HTTPS

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#399]
HTTPS-Only mode is flagging some sites that are already HTTPS.

REPRO STEPS:
- navigate to https://delta.com/
- see HTTPS-Only Mode Alert (see below)

![image](https://user-images.githubusercontent.com/1709237/100765317-5f936080-33c5-11eb-9d4e-51ed252a4eeb.png)

**Comment by chrmod** [comment]
https://delta.com does not load for me at all, maybe there in fact is some issue on their side.

**Comment by 2br-2b** [comment]
I've gotten the same problem myself, but reloading the page or clicking through brings me to the https site. I'd be willing to bet this is an upstream problem

**Comment by PoorPocketsMcNewHold** [comment]
Seems to be caused by the website in itself really. https://observatory.mozilla.org/analyze/delta.com

![](https://user-images.githubusercontent.com/13170204/101915685-3c875e80-3bc6-11eb-9839-b5c09a49b8a4.png)

**Comment by chrmod** [comment]
This is upstream issue and Mozilla for sure is improving this feature. I'm closing this issue for now.
