### ISSUE TITLE
Custom styling for about: dialog

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#41]
See: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-6414fb8f9ce84a4e9a742fbd993fae3fR16

Another way to change the appearance could be to replace the image asset instead of changing the stylesheet?

Further changes involve updating the content of the dialog with versions of the browser + extension: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-5f0366f67931908a5b65ed6cd46e1297R36-R51

**Comment by sammacbeth** [comment]
I think we'll stick with the current styling. #58 tracks the branding changes needed.
