### ISSUE TITLE
Update fails on mac aarch64

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/user-agent-desktop#424]
Updating to a universal binary version of the browser on mac breaks the install on ARM (M1) Macs. Intel macs are not affected.

After update the follow error is shown when launching the browser:
<img width="372" alt="Screen Shot 2020-12-29 at 11 07 25 AM" src="https://user-images.githubusercontent.com/248111/103298341-6a5c0800-49fa-11eb-8b72-6801b2fcf05f.png">

**Comment by fcjr** [comment]
Looks to be due to changes to code signature verification on the new M1 chips https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes

**Comment by sammacbeth** [comment]
I've now confirmed that using a mar with signed contents fixes this issue. #425 updates CI to repackage the mar from the signed DMG, meaning that the contents will be signed.
