### ISSUE TITLE
Customize data collection onboarding

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#43]
In Cliqz we had this as part of the onboarding: https://cliqztix.atlassian.net/browse/DB-2056
Diff: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-cef53509552274ae809ff183f3394680R2140

Maybe this should be part of the Ghostery onboarding?

**Comment by chrmod** [comment]
Closing for now as we've disable Firefox telemetry completery  https://github.com/ghostery/user-agent-desktop/blob/21d55824ab73940037344e846888a8e5c893c845/branding/ghostery/pref/firefox-branding.js#L61
