### ISSUE TITLE
Add PWA Support

### ISSUE THREAD

**Issue by 2br-2b** [ghostery/user-agent-desktop#467]
Mozilla has said that they will no longer be attempting to support PWAs in Firefox (https://www.fastcompany.com/90597411/mozilla-firefox-no-ssb-pwa-support). This has left many users (including myself) feeling frustrated (https://bugzilla.mozilla.org/show_bug.cgi?id=1682593 - look also at the collapsed comments).

It would take a lot of manpower, but could Ghostery add Progressive Web App (PWA) support? It would be a huge draw for many Firefox (and potentially Chromium) users. It's honestly one of the main reasons I almost didn't use Ghostery.

We can see other platforms (even OSes like Linux Mint - https://itsfoss.com/web-app-manager-linux-mint/) seeing the importance of web apps. Adding PWA support to Ghostery, a Firefox-based browser, would give a huge boost to Ghostery's popularity and hopefully increase their market share.

**Comment by chrmod** [comment]
This is interesting topic as I believe you reference one specific feature of PWA that Mozilla chosen to not push forward and its making website behave more like independent apps. We much sympathize with the idea and even tried to push it forward by enabling "Sites in App Mode" by default:
<img width="305" alt="Screenshot 2021-02-18 at 12 16 11" src="https://user-images.githubusercontent.com/1228153/108349283-180dbb00-71e3-11eb-8a9d-587c317cd074.png">
  
Unfortunately it is unlikely we will be able to offer this feature without Firefox support. Mozilla made it's choice based on careful evaluation and even though it upsets some community members (myself included) pushing it forward without substantial investment would create more problems. 
One example that could be a problem for Ghostery Dawn is how to deal with Adblocking/Anti-tracking in "standalone app": If we want to remove browser UI, there is no way users could control the adblocker behavior or even be aware of its activity. So natural choice would be to disable addons for PWA's which beats the purpose of using Ghostery Dawn.  

I'm closing the issue and it belongs rather to Mozilla than to Ghostery.
