### ISSUE TITLE
Glowstery.com new tab page privacy concern?

### ISSUE THREAD

**Issue by 2br-2b** [ghostery/user-agent-desktop#469]
Whenever a user opens a new tab, as seen in #468, it would seem that the browser establishes a connection to https://glowstery.com/.

This is fine, but isn't this also a privacy concern? After all, then Glowstery gets pinged every time a new tab is opened, letting them know the ip address of everyone using their browser.

An alternative could be just having the Glowstery page already loaded in the browser.

**Comment by chrmod** [comment]
Thank you for the report. 

Your concerns are very valid and even though we moved to a different approach of showing a new tab page (https://github.com/ghostery/user-agent-desktop/issues/468#issuecomment-771748594) I still want to explain that the previous one should really not rise any privacy considerations:
1. browser caches new tab page automatically - without going into details, this helps to show the page much faster
2. ghosterysearch.com uses caching headers so it browser can use regular http caching
3. there are no parameter send with the landing page request, no cookies, no tokens, no ids. The only thing that is there is IP (which is not taken into consideration for the caching mechanism so all users get the same cached http server response) 

Hope that this explanation helps.
