### ISSUE TITLE
"Firefox" appears instead of "Dawn" in French browser menus

### ISSUE THREAD

**Issue by wlycdgr** [ghostery/user-agent-desktop#482]
* Install French add-on pack
* Select French in preferences
* Restart to switch browser UI to French
* Observe that "Firefox" is used instead of "Dawn" in browser menus. E.g.:

![image](https://user-images.githubusercontent.com/29666909/107555038-b32fe080-6ba4-11eb-848e-99d859b83c65.png)

**Comment by chrmod** [comment]
This project does not support language packs and that's the source of the problem. We've changed some translation so the original Firefox language packs wont work, and it fact they may break a browser.

When you install French version all look fine:
<img width="242" alt="Screenshot 2021-02-11 at 09 06 47" src="https://user-images.githubusercontent.com/1228153/107613375-7a494780-6c48-11eb-8524-e462c827c616.png">

Closing in favor of https://github.com/ghostery/user-agent-desktop/issues/485
