### ISSUE TITLE
Switching languages with Firefox language add-ons causes crash hang

### ISSUE THREAD

**Issue by wlycdgr** [ghostery/user-agent-desktop#483]
I have been able to reproduce this 3/3 times (2x English -> French and French -> English) on macOS 10.15.6 Catalina. I have NOT been able to reproduce on Firefox 85.0.2 using the same steps as below.

* Uninstall Dawn by moving it to the trash from the Applications folder & remove the Application Support files as well
* Install Dawn using the `.dmg` linked in the README (currently `Ghostery-2021.02.en-US.mac-signed.dmg`)
* Update Dawn through About Dawn and restart to apply updates
* Install the French language add-on pack from https://addons.mozilla.org/en-US/firefox/addon/fran%C3%A7ais-language-pack/
* Switch to French in Preferences -> General tab -> Language
* Restart to apply language change
* Observe that Dawn hangs on launch

**Comment by chrmod** [comment]
Same as https://github.com/ghostery/user-agent-desktop/issues/482 - this project does not support Firefox language packs. So a proper solution is to disable them https://github.com/ghostery/user-agent-desktop/issues/485
