### ISSUE TITLE
When Dawn is the default browser and you click a link in another app, two Dawn windows open instead of one

### ISSUE THREAD

**Issue by wlycdgr** [ghostery/user-agent-desktop#488]
macOS Catalina

* Install Dawn
* Set Dawn as default browser
* Make sure Dawn is not running at all, not just that there are no open windows
* Click a link in some other app
* Observe that TWO Dawn windows open: one with just a new tab page, and one with a single tab containing the linked page

**Comment by wlycdgr** [comment]
This bug doesn't appear to be Dawn-specific. I can reproduce it not only in Firefox but also in Chrome, with links from both Slack and Discord. Could be an Electron bug, could be a Catalina bug.

**Comment by chrmod** [comment]
All good, thank you for the report!
