### ISSUE TITLE
Closing last tab does not close window

### ISSUE THREAD

**Issue by fcjr** [ghostery/user-agent-desktop#500]
On the latest dawn build, closing the last tab on a window no longer closes the window, it instead immediately reopens a new tab with the `new-tab` extension which is a bit annoying when wanting to close a window via `⌘+w` now you’re only able to close a window with `⌘+shift+w`.

**Comment by 2br-2b** [comment]
Can confirm, happens on Linux as well. Probably related to #484

**Comment by 2br-2b** [comment]
Yes, see https://github.com/ghostery/user-agent-desktop/pull/484/files#diff-8784cffcf225e747db519a90485b17053b9aef3a2673dd314322d98b6a8bbebcR367

**Comment by fcjr** [comment]
> Yes, see https://github.com/ghostery/user-agent-desktop/pull/484/files#diff-8784cffcf225e747db519a90485b17053b9aef3a2673dd314322d98b6a8bbebcR367

Yep thanks @2br-2b! @chrmod I personally find this frustrating as this behavior is not inline with any other browsers but if others have a strong desire to keep this change we can keep it as is. Thoughts?

**Comment by 2br-2b** [comment]
I prefer it where closing the last tab closes the window, but I'll wait to open a PR until we get more people weighing in on it.

**Comment by chrmod** [comment]
I'm also bit puzzled by this new behavior. I've realized I have a muscle memory for closing tabs and windows and this change broke it. 

@2br-2b would be great to get the PR :-)

**Comment by yokoffing** [comment]
> Can confirm, happens on Linux as well. Probably related to #484

@2br-2b, I am aware of this behavior. I put it in my `user.js` intentionally as it is a behavior only Firefox+forks can do, and it is something I prefer.

> is a bit annoying when wanting to close a window via `⌘+w` now you’re only able to close a window with `⌘+shift+w`.

@fcjr, I had not considered this.

> I'm also bit puzzled by this new behavior.

@chrmod, We can revert this to `false` to match the behavior of other browsers by default. This was one of my 'subjective-taste' prefs that got through 😋
