### ISSUE TITLE
New Tab page only shows search bar when Ghostery Search is enabled

### ISSUE THREAD

**Issue by 2br-2b** [ghostery/user-agent-desktop#503]
Right now, when my search engine is Ghostery Glow, I get this homepage:

![screenshot 01](https://user-images.githubusercontent.com/43968991/108261159-361ae300-7131-11eb-8343-ea73addc7863.png)

On the other hand, when I have any other search engine, the search bar disappears:

![screenshot 02](https://user-images.githubusercontent.com/43968991/108261231-55197500-7131-11eb-920f-1b2ad95bf728.png)

Could we enable this search bar to show whether or not you use Ghostery Glow? We could change the action on the page from `<form action="https://glowstery.com/search">` to `<form action="moz-extension://7e39925e-c927-4393-8b89-6996523e0bbe/search">`, and make the extension page redirect to the default search engine.

**Comment by chrmod** [comment]
It's debatable what the best choice here. Soon we will have new features on the new tab page that will show some privacy statistics there. In principle New Tab page is the only real estate Ghostery Dawn can communicate its values. And our main value is privacy. That is why we remove search bar, as it would send a mixed message and would mix the branding. 

BTW, we have followed Chromium behavior here - the search bar is only visible in Chromium if google.com is set as default search engine.

Besides we know that majority of users uses urlbar for searching. 

We still appropriate your suggestion, in this case however we have to prioritize Ghostery branding (in the end we are a new player in browser wars and we try to do our best to spread the knowledge about our products).
