### ISSUE TITLE
npm error on linux

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#507]
I've been making more than enough issues, and I've wanted to contribute, but I have the following error when trying to build.

I ran these commands:

```
git clone https://github.com/ghostery/user-agent-desktop/
cd user-agent-desktop
npm ci
```

I got the error at https://gist.github.com/2br-2b/8c5d9f7f0f683f3671ae7a8c844465ce

What is going wrong? I assumed it was an error with the wrong version of python with some feature not included in this version of python, hence the error `platform is not implemented yet`.

I'm running Linux Mint, and it seems to be trying to work with some macos files. I'm guessing that whatever it's trying to do is not supported on Linux and only on Macs and/or Windows.

This will be my first time contributing to Firefox or any of its forks, so I want to make sure I get the environment set up right.

Thank you for your help!

_Originally posted by @2br-2b in https://github.com/ghostery/user-agent-desktop/discussions/497_

**Comment by remusao** [comment]
After some further investigation it seems like the issue is from `appdmg` which is not compatible with Linux (I think?). When removing it from package.json and running `npm install` the issue is gone. A possible fix is to remove it from package.json and use `npx appdmg` from `sign_mac.sh` for CI.
