### ISSUE TITLE
Build server IPFS setup

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#555]
One of the build server (kria) hosts IPFS gateway that we use to download some of the build prerequisites like PGO profiles. 

After system restart we have to manually start IPFS daemon which is inconvenient.  

Ideally we would host IPFS gateway on public server. Or migrate to other solution.

**Comment by y3ti** [comment]
IPFS was migrated to Amazon S3: https://github.com/ghostery/user-agent-desktop/issues/555
