### ISSUE TITLE
Build servers: remove cliqznas dependency

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#556]
Two potentials ways forward: 
* use ipfs, but it's unclear if we can put windows SDK there
* use s3 buckets, windows SDK may be put on a private one

**Comment by y3ti** [comment]
I think it's done: https://github.com/ghostery/user-agent-desktop/pull/583 https://github.com/ghostery/user-agent-desktop/pull/584 https://github.com/ghostery/user-agent-desktop/pull/590
