### ISSUE TITLE
Update rights page (about:rights)

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/user-agent-desktop#57]
`about:rights` has firefox-specific copy.

**Comment by sammacbeth** [comment]
Current copy:
<img width="714" alt="Screenshot 2020-09-14 at 17 37 51" src="https://user-images.githubusercontent.com/248111/93106793-0adb2600-f6b1-11ea-9cbb-47774bf7eced.png">

**Comment by chrmod** [comment]
lets not change it for now
