### ISSUE TITLE
About Dialog branding

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/user-agent-desktop#58]
<img width="642" alt="Screenshot 2020-07-30 at 16 22 37" src="https://user-images.githubusercontent.com/248111/88936335-18645a00-d283-11ea-9672-3d27e2a546f0.png">

- [ ] Title should be 'Ghostery'
- [ ] Remove mozilla copy under the update channel
- [x] Update privacy policy link.

**Comment by sammacbeth** [comment]
After #116 the about page now looks like this:
![Screenshot 2020-09-11 at 11 02 01](https://user-images.githubusercontent.com/248111/92898473-4ad6aa80-f41e-11ea-8cf4-e3f06e75f791.png)

There remains:
 * #56 to update the contents when following the 'Licensing Information' link to `about:licences`
 * #57 to update the consents when following the 'End-User Rights' link to `about:rights`
 * #108 should update the icon and 'Nightly' text.

**Comment by chrmod** [comment]
Need to update the assets.
