### ISSUE TITLE
Selecting "Take Screenshot" in context menu fails

### ISSUE THREAD

**Issue by colinje** [ghostery/user-agent-desktop#580]
Steps to repro:
1) Go to npr.org
2) Right click any whitespace
3) Left click "Take Screenshot"
4) Nothing happens. Expected modal of screenshot with copy/save buttons like stable Firefox.

**Comment by chrmod** [comment]
Screenshots are optional feature of Firefox which is not included in Ghostery Dawn. It's removed in this patch. 
https://github.com/ghostery/user-agent-desktop/blob/main/patches/0005-Remove-bundled-mozilla-extensions.patch#L19

Looks like the context menu for the screenshots was introduced fairly recently and it fails as the required system addon is missing. 

At this point of time we can do one of the two:
1. remove the context menu
2. re-introduce the screenshots system addon


I'm leaning towards the later. 

Marking it as a bug to be resolved in upcoming release.


Thanks for the report @colinje

**Comment by colinje** [comment]
Until you're able to mark-up screenshots, I personally would remove it from context menu.
