### ISSUE TITLE
Snap packaging

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#581]

**Comment by Techogntio** [comment]
Would love to see Dawn on flathub aswell

**Comment by huuhaa** [comment]
@Techognito Exactly, for both, flatpak to flathub as well. I'm personally not gonna install snap even if available, but it's good to have for those who want to. But otoh there's also Librewolf available and for a long time I just tested Ghostery once again and updated it, havwn't used for a long time. Might let it be installed as flatpak (if available), but might remove my typical installation soon.

**Comment by philipp-classen** [comment]
For Flatpak, see https://github.com/ghostery/ghostery-browser-linux-support/pull/4/files

**Comment by philipp-classen** [comment]
Flatpak package: https://flathub.org/apps/com.ghostery.browser

**Comment by chrmod** [comment]
Closing for now
