### ISSUE TITLE
graad.eu has broken CSS

### ISSUE THREAD

**Issue by yokoffing** [ghostery/user-agent-desktop#582]
https://github.com/yokoffing/Better-Fox/issues/44

@chrmod @2br-2b , this is affecting Ghostery Browser as well. Can you help me isolate this issue?

**Comment by chrmod** [comment]
Interesting. Looks like we don't load stylesheets that are marked for `preloading`

```html
<link onload="this.rel='stylesheet'" rel="preload" as="style" href="/site/custom.1.0/theme/css/fonts/css/all.min.css"  />
<link onload="this.rel='stylesheet'" rel="preload" as="style" href="/site/custom.1.0/theme/css/default.css"  />
<link onload="this.rel='stylesheet'" rel="preload" as="style" href="/site/custom.1.0/theme/css/theme.css"  />
<link onload="this.rel='stylesheet'" rel="preload" as="style" href="/site/custom.1.0/theme/css/queries.css" />
<link onload="this.rel='stylesheet'" rel="preload" as="style" href="/custom/theme.css"  />
```

**Comment by chrmod** [comment]
flipping `network.preload` to `true` fixes the problem.

I'm closing this issue, lets continue to discuss at the original one https://github.com/yokoffing/Better-Fox/issues/44
