### ISSUE TITLE
Preference: remove "Home Content" settings

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/user-agent-desktop#60]
<img width="940" alt="Screenshot 2020-07-30 at 17 04 11" src="https://user-images.githubusercontent.com/248111/88939398-c4f40b00-d286-11ea-9d96-d73e54aa3bfe.png">

**Comment by sammacbeth** [comment]
Reopening this as we should probably remove this section of the preferences now we are forcing our custom new tab page via #115. As mentioned in #179 we should decide whether this page should be changeable or not.

**Comment by sammacbeth** [comment]
At least the 'Firefox Home Content' section should be hidden, or re-branded.

**Comment by chrmod** [comment]
Lets keep the "New Window and Tabs" and remove the "Firefox home content" sections.

Obviously all "Firefox" strings should be replaced.
