### ISSUE TITLE
Ghostery Dawn 2022.8.1 (dc13da3) (64-bit) for Windows: update loop

### ISSUE THREAD

**Issue by KNTRO** [ghostery/user-agent-desktop#618]
Hi all.

There's a bug with this version of Ghostery Dawn. Since its update to version 2022.8.1, it has an update loop. I contacted with Ghostery support and they told me to uninstall Ghostery Dawn and reinstall it. I did it so but it didn't work. You can watch this behavior in [this video on YouTube](https://www.youtube.com/watch?v=W_bdDiTQQHg).

My OS is Windows 10 Home, Version 20H2 (Build OS 19042.1466), 64-bit.

Thank you very much for reading.

**Comment by KNTRO** [comment]
Looks like version 2022.8.2 (a6056a5) has solved this issue. I will wait for a few days before closing this.

**Comment by GRadziejewski** [comment]
Not reproducible any more on version https://github.com/ghostery/user-agent-desktop/commit/1db7cb476225a769c1ef35330bc39b0d73dffa65
