### ISSUE TITLE
What is a linux x86 64 .mar binary?

### ISSUE THREAD

**Issue by BarbzYHOOL** [ghostery/user-agent-desktop#624]
Hello,

sorry if a bit offtopic but I have never seen this before,
what is a .mar binary for linux?
such as `Ghostery-2022.8.2.de.linux-x86_64.complete.mar `

and how to use it if it's fine?

**Comment by chrmod** [comment]
.MAR file format is used by Mozilla to ship Firefox updates. It is basically an encrypted zip. You can read a bit more here https://wiki.mozilla.org/Software_Update:MAR
