### ISSUE TITLE
Update branding to Ghostery Private Browser

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#627]
source files:

* [ ] `bgstub.jpg`
![Image](https://user-images.githubusercontent.com/1228153/214839594-9688c0b2-ea06-4e87-a71c-6940e47be59f.jpg)
`JPEG image data, baseline, precision 8, 2551x1668, components 3`

* [ ] `about.png`
![Image](https://user-images.githubusercontent.com/1228153/214839330-b84336a6-fc8e-4d31-ac1b-d806484e75b0.png)
`PNG image data, 300 x 236, 8-bit/color RGBA, non-interlaced`

* [ ] MacOS icons
[Icons.zip](https://github.com/ghostery/user-agent-desktop/files/10509366/Archive.zip)

* [ ] `horizontal-lockup.svg`
![Image](https://user-images.githubusercontent.com/1228153/214840173-2d94c964-9c86-49cb-a917-cfe7924d4542.svg)

* [ ] Other SVGs (need to be checked)
[svgs.zip](https://github.com/ghostery/user-agent-desktop/files/10509429/svgs.zip)

**Comment by kalinme** [comment]
[Updated Assets.zip](https://github.com/ghostery/user-agent-desktop/files/10511626/Updated.Assets.zip)

@chrmod please check these assets. I hope everything is fine ;)

**Comment by chrmod** [comment]
required for https://github.com/ghostery/user-agent-desktop/pull/626
