### ISSUE TITLE
Redesign: Privacy Browser New Tab

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#628]
statistical report leads user to WTM main page --> completely lost

![Image](https://user-images.githubusercontent.com/116146386/209190355-45b63f80-1684-45d5-a210-6e0617a2a907.png)

https://whotracks.me/

**Comment by GRadziejewski** [comment]
It looks like this in version: https://github.com/ghostery/user-agent-desktop/commit/1db7cb476225a769c1ef35330bc39b0d73dffa65
![image](https://github.com/ghostery/user-agent-desktop/assets/40433708/84e2716c-fdc2-4924-bf72-55ff85140e20)
