### ISSUE TITLE
Window task bar name

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#63]
Change some Mozilla hard-coded string: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-6512571d1985f28886c4d0b895453b7dR245

**Comment by chrmod** [comment]
@sammacbeth why this got closed?

**Comment by sammacbeth** [comment]
> @sammacbeth why this got closed?

Same as https://github.com/ghostery/user-agent-desktop/issues/64#issuecomment-698249440
