### ISSUE TITLE
Firefox Home (Default) setting is visible

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/user-agent-desktop#633]
**Description**
There is Firefox Home (Default) setting for "Homepage and new windows" and "New tabs".

**Steps to Reproduce**
1. Open about:preferences and search "Firefox"
![obraz](https://user-images.githubusercontent.com/40433708/220304970-6b4e179a-befd-4e46-9d14-dbca8cfc0ba9.png)

**Expected Results:**
Firefox Home (Default) setting should not be visible.

**Versions:**
Browser: Ghostery Private Browser 2023.1 (939ec97)
OS: Windows 10 Pro 19045.2604

Browser: Ghostery Private Browser 2023.1 (c751323)
OS: macOS Ventura 13.2

**Comment by chrmod** [comment]
Good catch. That's what you get from removing interface with CSS ;)

**Comment by GRadziejewski** [comment]
Not reproducible any more.
