### ISSUE TITLE
Not changed name for Ghostery Private Search

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/user-agent-desktop#634]
**Description**
Not changed name for Ghostery Private Search after clicking on the icon of this feature.

**Steps to Reproduce**
1. Focus the cursor on the icon and press it
![obraz](https://user-images.githubusercontent.com/40433708/220306138-f7a5a263-de87-4626-be5f-de9476f9a942.png)
2. Look at the text - there is "Ghostery Glow"
![obraz](https://user-images.githubusercontent.com/40433708/220306408-273cb314-9567-4d40-9351-600fe570776e.png)

**Expected Results:**
It should be changed to Ghoster Private Search

**Versions:**
Browser: Ghostery Private Browser 2023.1 (939ec97)
OS: Windows 10 Pro 19045.2604

Browser: Ghostery Private Browser 2023.1 (c751323)
OS: macOS Ventura 13.2

**Comment by chrmod** [comment]
The new name is Ghostery Private Search. It is the search that needs a rebranding :)
