### ISSUE TITLE
Native windows class names

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#64]
Hard-coded values changed here: https://github.com/human-web/user-agent-desktop/pull/6/files#diff-cf7441765c12fc2d98d0e7c56a0a65dfR68-R73

Maybe relevant as well:
* https://github.com/human-web/user-agent-desktop/pull/6/files#diff-b70b3609096de2dcbbd0b634f249d69fR1014
* https://github.com/human-web/user-agent-desktop/pull/6/files#diff-1d64218bd74210a722243a0afdcb2ff5R719

**Comment by chrmod** [comment]
@sammacbeth why this got closed?

**Comment by sammacbeth** [comment]
We don't know what change this refers to, but from the title I guess this is a duplicate of https://github.com/ghostery/user-agent-desktop/issues/122
