### ISSUE TITLE
Updated Firefox version

### ISSUE THREAD

**Issue by printedz** [ghostery/user-agent-desktop#647]
Hello! The user agent of the browser is Firefox 109, however that's outdated and, probably, unsafe; wouldn't it be better to base it on ESR? Or update the Firefox version it's based on more often?

**Comment by RasheedAZ** [comment]
I came here for the same issue... Firefox latest stable is 122 while esr is 115 while Ghostery is based on 118 four versions back! This is unacceptable security risk for a web browser.

Please rebase Ghostery on Firefox ESR.

**Comment by GRadziejewski** [comment]
The latest version will be with user agent version 125. Closing.
