### ISSUE TITLE
Update driver (Windows XP)

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#65]
https://github.com/human-web/user-agent-desktop/pull/6/files#diff-6e7111c9429c7c71f4035f437dc1c84aR62

Seems like this might only be needed for Windows XP, in which case let's close it after someone can confirm. @sammacbeth @chrmod

**Comment by chrmod** [comment]
@sammacbeth why this got closed?

**Comment by sammacbeth** [comment]
> @sammacbeth why this got closed?

Same as https://github.com/ghostery/user-agent-desktop/issues/67#issuecomment-698247226
