### ISSUE TITLE
desktop browser not downloading documents

### ISSUE THREAD

**Issue by psdmcc** [ghostery/user-agent-desktop#664]
Hi, 

I've downloaded the browser 023.10 (8c707c3) (64-bit) and have issue with it not allowing documents to download such as pdfs.

In download history it just says 'failed'. 

Any suggestions?

big sur
11.7.10 (20G1427)

**Comment by GRadziejewski** [comment]
Not reproducible on version https://github.com/ghostery/user-agent-desktop/commit/1db7cb476225a769c1ef35330bc39b0d73dffa65
