### ISSUE TITLE
Update policy check (Windows XP)

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#67]
https://github.com/human-web/user-agent-desktop/pull/6/files#diff-c34d5fd656306434dce3369131a0f0adR20

Probably legacy (enclosed in a Windows XP check). Can someone confirm this before closing? @sammacbeth

**Comment by chrmod** [comment]
@sammacbeth Why this got closed? Is it not relevant anymore or already covered?

**Comment by sammacbeth** [comment]
> @sammacbeth Why this got closed? Is it not relevant anymore or already covered?

 1. We cannot recover the diff this is talking about
 2. This refers to winXP only code, which we will not support anyway.
