### ISSUE TITLE
[QA] Tests of 2024-05

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/user-agent-desktop#685]
Tests of: https://github.com/ghostery/user-agent-desktop/releases/tag/2024-05-20

**Comment by GRadziejewski** [comment]
## Smoke tests Iteration no 1:



## Issues:
- 

## Fixed:
- 

## Cannot reproduce:
- 

**Tests are finished at ....**

|| Feature 									|  Browser |
|:--- | 	 :---									| :---: |
| NO | X  										|  Windows 10 |
|01| Install fresh (no profiles etc) 					|
|02| Update 									|
|03| Ghostery cannot work before onboarding  		|
|04| Onboarding 								|
|05| Enable/Disable Ghostery 					|️
|06| Enable/Disable Ad-blocking  					|
|07| &emsp;  Trust / block the tracker  				|
|08| Enable/Disable Anti-tracking  					|
|09| &emsp;  All blocked 3 main categories  			|
|10| &emsp; &emsp; Advertising  					|
|11| &emsp; &emsp; Site Analytics  				|
|12| &emsp; &emsp; Adult Advertising  			|
|13| &emsp;  Trust / block the tracker  				|
|14| Pause Ghostery  							|
|15| Enable/Disable Never Consent  				|
|16| Trackers Preview  							|
|17| Restart the browser							|
|18| Licences 									|
|19| Language (ENG, FR, etc)						|
|20| Uninstall survey							|
|21| Sign in/out  								|
|22| &emsp; Sign in and then update  				|
|22| &emsp; Check Sync from / into another device	|
|23| &emsp;&emsp; Check Ghostery Background logs 	|
|24| &emsp; Check Ghostery account settings		|
|25| Check settings								|
|26| &emsp; Trackers database / menu				|
|26| &emsp;  &emsp; Sing in and check Trackers database / menu 		|
|27| &emsp;  &emsp; &emsp; (sync)				|🟦
|28| Log into Google account and open google.com 	|
|29| &emsp; Try to search for anything				|
|30| &emsp; Try to search something with video		|

```
Browser: Ghsotery Private Browser 2024-05
OS: Windows 10 Pro
GBE 10.3.2

```

Legend:
- ✔️ - Checked and working
- ❌ - Issue
- 🟦 - Not available 
- 🟨 - Not tested

**Comment by GRadziejewski** [comment]
When clicked, a pop-up window inside the frame will open.

https://github.com/ghostery/user-agent-desktop/assets/40433708/e61b37b2-6ac4-49ad-817c-4016ed3bad38

**Comment by smalluban** [comment]
> Expected results:
> Nothing should happen.

This is not correct. When a user clicks on the wheel popover shows up, which is fine - the wrapper element should not have a scrollbar etc... However, I am not able to reproduce it on macOS.

<img width="604" alt="Zrzut ekranu 2024-05-21 o 14 56 34" src="https://github.com/ghostery/user-agent-desktop/assets/1906677/a12e4e54-fe54-49a9-92ea-62e77aae205a">

**Comment by smalluban** [comment]
Updated newtab-extension fixes the issue: https://github.com/ghostery/ghostery-newtab-extension/releases/tag/v1.0.2

**Comment by GRadziejewski** [comment]
## Smoke tests Iteration no 2:
Tests of : https://github.com/ghostery/user-agent-desktop/releases/tag/2024-05-21


## Issues:
- 

## Fixed:
- [[01] a pop-up window inside the frame will open.](https://github.com/ghostery/user-agent-desktop/issues/685#issuecomment-2120651737)

## Cannot reproduce:
- 

**Tests are finished at ...**

|| Feature 									|  Browser |
|:--- | 	 :---									| :---: |
| NO | X  										|  Windows 10 |
|01| Install fresh (no profiles etc) 					|🟨
|02| Update 									|🟨
|...| ...		|...
|30| &emsp; Try to search something with video		|🟨
| NO | ---  									| --- |
|31| Browser installation 						|
|32| &emsp; Update 							|
|33| &emsp; Language (ENG, FR, DE)				|
|34| Browser settings and menus  					|
|35| &emsp; Bookmarks, History  					|
|36| &emsp; Help  								|
|37| &emsp; Ghost Mode  						|
|38| &emsp; Passwords 							|
|39| Ghostery search 							|
|40| Commonly visited pages 					|
|41| Uninstall survey							|

```
Browser: Ghsotery Private Browser 2024.05 (df7fe53)
OS: Windows 10 Pro
GBE 10.3.2

```

Legend:
- ✔️ - Checked and working
- ❌ - Issue
- 🟦 - Not available 
- 🟨 - Not tested

**Comment by GRadziejewski** [comment]
Issue no 02

**Description**
During import of data from other browsers, the Firefox browser icon is replaced by our icon.


**Steps to Reproduce**

1. Open Settings
2. 

![image](https://github.com/ghostery/user-agent-desktop/assets/40433708/9fc77789-f3ad-4a60-a35e-63ab54fb7e1d)


**Expected results:**
The Firefox browser icon should not be replaced by our icon.

**Comment by GRadziejewski** [comment]
## Smoke tests Iteration no 4:
Tests of : https://github.com/ghostery/user-agent-desktop/releases/tag/2024-05-30


## Issues:
- 

## Fixed:
- 

## Cannot reproduce:
- 

**Tests are finished at ...**

|| Feature 									|  Browser |Browser |
|:--- | 	 :---									| :---: | :---: |
| NO | X  										|  Windows 10 | MacOS |
|01| Install fresh (no profiles etc) 					|🟨|🟨
|02| Update 									|🟨|🟨
|...| ...											| ... | ...
|30| &emsp; Try to search something with video		|🟨|🟨
| NO | ---  									| --- | --- |
|31| Browser installation 							|
|32| &emsp; Update 							|
|33| &emsp; Language (ENG, FR, DE)				|
|34| Browser settings and menus  					|
|35| &emsp; Bookmarks, History  					|
|36| &emsp; Help  								|
|37| &emsp; Ghost Mode  						|
|38| &emsp; Passwords 							|
|39| Ghostery search 							|
|40| Commonly visited pages 						|
|41| Uninstall survey								|

```
Browser: Ghsotery Private Browser 2024.05 ()
OS: Windows 10 Pro
GBE 10.3.3

Browser: Ghsotery Private Browser 2024.05 ()
OS: MacOS 14.5 
GBE 10.3.3

```

Legend:
- ✔️ - Checked and working
- ❌ - Issue
- 🟦 - Not available 
- 🟨 - Not tested
