### ISSUE TITLE
Two issues with Ghostery Private Browser 2024.05 (15b7185) (64-bit) for Windows

### ISSUE THREAD

**Issue by KNTRO** [ghostery/user-agent-desktop#690]
Hello,

Since this new version, I'm facing two issues with Ghostery Private Browser.

The first issue happens every single time I run Ghostery. Just after the Ghostery window appears, it eats a lot of both CPU and RAM for around 10~15 seconds, and no webpage will load during that period. A possible memory leak, perhaps? 🤔

And the second issue comes now.

I thought: "_OK, it might be an add-on, so I'm going to try running Ghostery under Troubleshoot Mode_". So I go to Help > Troubleshoot Mode, click on the Restart button, and Ghostery closes… but never restarts. 😝 I open the Windows' Task Manager and can confirm that Ghostery is still running on the background, so it closes the window but doesn't completely close the whole process.

Hope you can fix these issues.

Kind regards.

**Comment by chrmod** [comment]
@KNTRO thank you for reporting. A new release is on the way, we hope to address those in upcoming days.

**Comment by GRadziejewski** [comment]
@KNTRO Thank you for your report. 
The problem with the troubleshooting mode has been fixed in the latest version. So please be patient, it should be available soon.

The other issue you mentioned - CPU and RAM usage - I can't reproduce this situation. Can you elaborate a bit more on what is happening, what you are doing? Can you share some screenshots? Thank you kindly!

**Comment by KNTRO** [comment]
Hello @GRadziejewski!

After testing a little bit, I've found out that the initial issue was not related to CPU and RAM usage ony, but to drive usage too! [I have just uploaded a video at YouTube](https://www.youtube.com/watch?v=shngVfroPe4), where you will notice that:

- Ghostery won't load a webpage for several seconds (it's kind of frozen — Please, check the CPU usage)
- Disk usage is high and constant for several seconds (some days ago, it skyrocketed up to 4.8 MB/s! 🤯)
- After the webpage is finally loaded, both CPU and disk usage calm down

Hope this helps! 🙏

**Comment by GRadziejewski** [comment]
Thank you for more information! :)

So I started by opening our browser, and then immediately tried opening the ddg.gg you showed, and the website opened within a second or two. I can see some spikes in CPU, RAM, hard drive and Ethernet usage, but everything dropped. Just as you described. 
I have tested this on my Windows 10 virtual machine and also normally on Windows 10. Perhaps there is a difference as we have recently released a new version?

At the same time, maybe this is silly, but I see in the video provided that you have additional browser extensions installed in your browser. Unfortunately, I don't recall some of them, so I can't 100% replicate your environment. I checked with the Proton Pass and Dark Reader extensions installed, I even managed to find a browser theme. But the results at the end are the same.

![image](https://github.com/ghostery/user-agent-desktop/assets/40433708/6d5d6feb-5d8a-4b05-9dfa-fc9cb5ea68c0)

@KNTRO Can I ask you to check if the new version makes any change on your side?

**Comment by KNTRO** [comment]
@GRadziejewski Hello there! 👋

I'm using Ghostery 2024.05.1 (86f09cb) (64-bit) now. For the time being, there is no high CPU usage, nor high RAM usage, nor high disk usage either. 😃 So, I will close this issue. 😉

Thank you for taking all that time testing these things. I'm glad that Ghostery is now working as good as always! 😌
