### ISSUE TITLE
Remove about:logins

### ISSUE THREAD

**Issue by remusao** [ghostery/user-agent-desktop#76]
- [ ] https://github.com/human-web/user-agent-desktop/pull/6/files#diff-1eb0c12c4f46fd0466d09616d55bf358R58
- [ ] https://github.com/human-web/user-agent-desktop/pull/6/files#diff-ce805829abadd4f57377251c953b9344R15

**Comment by chrmod** [comment]
Duplicate of https://github.com/ghostery/user-agent-desktop/issues/166
